# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EnteteDetailWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnteteDetailWidget(object):
    def setupUi(self, EnteteDetailWidget):
        EnteteDetailWidget.setObjectName("EnteteDetailWidget")
        EnteteDetailWidget.resize(816, 644)
        self.widgetCentral = QtWidgets.QWidget(EnteteDetailWidget)
        self.widgetCentral.setGeometry(QtCore.QRect(9, 9, 761, 626))
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widgetContainerButton = QtWidgets.QWidget(self.widgetCentral)
        self.widgetContainerButton.setMinimumSize(QtCore.QSize(93, 621))
        self.widgetContainerButton.setObjectName("widgetContainerButton")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetContainerButton)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonNouveau = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.verticalLayout.addWidget(self.pushButtonNouveau)
        self.pushButtonValider = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonValider.setObjectName("pushButtonValider")
        self.verticalLayout.addWidget(self.pushButtonValider)
        self.pushButtonRechercher = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonRechercher.setEnabled(False)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.verticalLayout.addWidget(self.pushButtonRechercher)
        self.pushButtonModifier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonModifier.setEnabled(False)
        self.pushButtonModifier.setObjectName("pushButtonModifier")
        self.verticalLayout.addWidget(self.pushButtonModifier)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonSupprimer.setEnabled(False)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.verticalLayout.addWidget(self.pushButtonSupprimer)
        self.pushButtonPremier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonPremier.setObjectName("pushButtonPremier")
        self.verticalLayout.addWidget(self.pushButtonPremier)
        self.pushButtonDernier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonDernier.setObjectName("pushButtonDernier")
        self.verticalLayout.addWidget(self.pushButtonDernier)
        self.pushButtonAvant = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonAvant.setEnabled(False)
        self.pushButtonAvant.setObjectName("pushButtonAvant")
        self.verticalLayout.addWidget(self.pushButtonAvant)
        self.pushButtonArriere = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonArriere.setEnabled(False)
        self.pushButtonArriere.setObjectName("pushButtonArriere")
        self.verticalLayout.addWidget(self.pushButtonArriere)
        self.pushButtonImprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimer.setEnabled(True)
        self.pushButtonImprimer.setObjectName("pushButtonImprimer")
        self.verticalLayout.addWidget(self.pushButtonImprimer)
        self.pushButtonImprimerTout = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimerTout.setEnabled(True)
        self.pushButtonImprimerTout.setObjectName("pushButtonImprimerTout")
        self.verticalLayout.addWidget(self.pushButtonImprimerTout)
        self.pushButtonVisualiser = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonVisualiser.setObjectName("pushButtonVisualiser")
        self.verticalLayout.addWidget(self.pushButtonVisualiser)
        spacerItem = QtWidgets.QSpacerItem(20, 314, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_16.addWidget(self.widgetContainerButton)
        self.scrollAreaContainerForm = QtWidgets.QScrollArea(self.widgetCentral)
        self.scrollAreaContainerForm.setWidgetResizable(True)
        self.scrollAreaContainerForm.setObjectName("scrollAreaContainerForm")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 642, 606))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxEntete = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxEntete.setObjectName("groupBoxEntete")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxEntete)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCodeCmd = QtWidgets.QLabel(self.groupBoxEntete)
        self.labelCodeCmd.setMouseTracking(True)
        self.labelCodeCmd.setObjectName("labelCodeCmd")
        self.horizontalLayout.addWidget(self.labelCodeCmd)
        self.lineEdit_int_CodeCmd = QtWidgets.QLineEdit(self.groupBoxEntete)
        self.lineEdit_int_CodeCmd.setEnabled(False)
        self.lineEdit_int_CodeCmd.setObjectName("lineEdit_int_CodeCmd")
        self.horizontalLayout.addWidget(self.lineEdit_int_CodeCmd)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCodeFournisseur = QtWidgets.QLabel(self.groupBoxEntete)
        self.labelCodeFournisseur.setMouseTracking(True)
        self.labelCodeFournisseur.setObjectName("labelCodeFournisseur")
        self.horizontalLayout_2.addWidget(self.labelCodeFournisseur)
        self.comboBoxCodeFournisseur = QtWidgets.QComboBox(self.groupBoxEntete)
        self.comboBoxCodeFournisseur.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxCodeFournisseur.setObjectName("comboBoxCodeFournisseur")
        self.horizontalLayout_2.addWidget(self.comboBoxCodeFournisseur)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelDateCmd = QtWidgets.QLabel(self.groupBoxEntete)
        self.labelDateCmd.setMouseTracking(True)
        self.labelDateCmd.setObjectName("labelDateCmd")
        self.horizontalLayout_3.addWidget(self.labelDateCmd)
        self.dateEditDateCmd = QtWidgets.QDateEdit(self.groupBoxEntete)
        self.dateEditDateCmd.setObjectName("dateEditDateCmd")
        self.horizontalLayout_3.addWidget(self.dateEditDateCmd)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBoxEntete)
        self.groupBoxDetail = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxDetail.setObjectName("groupBoxDetail")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxDetail)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 3, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelPrixGlobal = QtWidgets.QLabel(self.groupBoxDetail)
        self.labelPrixGlobal.setMouseTracking(True)
        self.labelPrixGlobal.setObjectName("labelPrixGlobal")
        self.horizontalLayout_15.addWidget(self.labelPrixGlobal)
        self.lineEdit_float_PrixGlobal = QtWidgets.QLineEdit(self.groupBoxDetail)
        self.lineEdit_float_PrixGlobal.setEnabled(False)
        self.lineEdit_float_PrixGlobal.setObjectName("lineEdit_float_PrixGlobal")
        self.horizontalLayout_15.addWidget(self.lineEdit_float_PrixGlobal)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_15, 2, 5, 1, 6)
        self.tableWidgetDetailDisplay = QtWidgets.QTableWidget(self.groupBoxDetail)
        self.tableWidgetDetailDisplay.setRowCount(0)
        self.tableWidgetDetailDisplay.setObjectName("tableWidgetDetailDisplay")
        self.tableWidgetDetailDisplay.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDetailDisplay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDetailDisplay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDetailDisplay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDetailDisplay.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDetailDisplay.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDetailDisplay.setHorizontalHeaderItem(5, item)
        self.tableWidgetDetailDisplay.verticalHeader().setVisible(False)
        self.tableWidgetDetailDisplay.verticalHeader().setHighlightSections(True)
        self.gridLayout.addWidget(self.tableWidgetDetailDisplay, 3, 0, 1, 11)
        self.pushButtonSupprimerDetail = QtWidgets.QPushButton(self.groupBoxDetail)
        self.pushButtonSupprimerDetail.setEnabled(False)
        self.pushButtonSupprimerDetail.setObjectName("pushButtonSupprimerDetail")
        self.gridLayout.addWidget(self.pushButtonSupprimerDetail, 4, 10, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelPrixUnitaire = QtWidgets.QLabel(self.groupBoxDetail)
        self.labelPrixUnitaire.setMouseTracking(True)
        self.labelPrixUnitaire.setObjectName("labelPrixUnitaire")
        self.horizontalLayout_13.addWidget(self.labelPrixUnitaire)
        self.lineEdit_float_PrixUnitaire = QtWidgets.QLineEdit(self.groupBoxDetail)
        self.lineEdit_float_PrixUnitaire.setObjectName("lineEdit_float_PrixUnitaire")
        self.horizontalLayout_13.addWidget(self.lineEdit_float_PrixUnitaire)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_13, 1, 5, 1, 6)
        self.pushButtonInsererDetail = QtWidgets.QPushButton(self.groupBoxDetail)
        self.pushButtonInsererDetail.setEnabled(False)
        self.pushButtonInsererDetail.setObjectName("pushButtonInsererDetail")
        self.gridLayout.addWidget(self.pushButtonInsererDetail, 4, 2, 1, 1)
        self.pushButtonAjouterDetail = QtWidgets.QPushButton(self.groupBoxDetail)
        self.pushButtonAjouterDetail.setObjectName("pushButtonAjouterDetail")
        self.gridLayout.addWidget(self.pushButtonAjouterDetail, 4, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelQuantite = QtWidgets.QLabel(self.groupBoxDetail)
        self.labelQuantite.setMouseTracking(True)
        self.labelQuantite.setObjectName("labelQuantite")
        self.horizontalLayout_12.addWidget(self.labelQuantite)
        self.lineEdit_float_Quantite = QtWidgets.QLineEdit(self.groupBoxDetail)
        self.lineEdit_float_Quantite.setObjectName("lineEdit_float_Quantite")
        self.horizontalLayout_12.addWidget(self.lineEdit_float_Quantite)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 0, 1, 5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelIdCmd = QtWidgets.QLabel(self.groupBoxDetail)
        self.labelIdCmd.setMouseTracking(True)
        self.labelIdCmd.setObjectName("labelIdCmd")
        self.horizontalLayout_10.addWidget(self.labelIdCmd)
        self.lineEdit_int_IdCmd = QtWidgets.QLineEdit(self.groupBoxDetail)
        self.lineEdit_int_IdCmd.setEnabled(False)
        self.lineEdit_int_IdCmd.setObjectName("lineEdit_int_IdCmd")
        self.horizontalLayout_10.addWidget(self.lineEdit_int_IdCmd)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 6)
        self.pushButtonModifierDetail = QtWidgets.QPushButton(self.groupBoxDetail)
        self.pushButtonModifierDetail.setEnabled(False)
        self.pushButtonModifierDetail.setObjectName("pushButtonModifierDetail")
        self.gridLayout.addWidget(self.pushButtonModifierDetail, 4, 4, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 4, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelRefProduit = QtWidgets.QLabel(self.groupBoxDetail)
        self.labelRefProduit.setMouseTracking(True)
        self.labelRefProduit.setObjectName("labelRefProduit")
        self.horizontalLayout_11.addWidget(self.labelRefProduit)
        self.comboBoxRefProduit = QtWidgets.QComboBox(self.groupBoxDetail)
        self.comboBoxRefProduit.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxRefProduit.setObjectName("comboBoxRefProduit")
        self.horizontalLayout_11.addWidget(self.comboBoxRefProduit)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 6, 1, 5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelDateLivraison = QtWidgets.QLabel(self.groupBoxDetail)
        self.labelDateLivraison.setMouseTracking(True)
        self.labelDateLivraison.setObjectName("labelDateLivraison")
        self.horizontalLayout_14.addWidget(self.labelDateLivraison)
        self.dateEditDateLivraison = QtWidgets.QDateEdit(self.groupBoxDetail)
        self.dateEditDateLivraison.setObjectName("dateEditDateLivraison")
        self.horizontalLayout_14.addWidget(self.dateEditDateLivraison)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_14, 2, 0, 1, 5)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 4, 9, 1, 1)
        self.pushButtonEffacerDetail = QtWidgets.QPushButton(self.groupBoxDetail)
        self.pushButtonEffacerDetail.setEnabled(False)
        self.pushButtonEffacerDetail.setObjectName("pushButtonEffacerDetail")
        self.gridLayout.addWidget(self.pushButtonEffacerDetail, 4, 8, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 4, 7, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBoxDetail)
        self.scrollAreaContainerForm.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_16.addWidget(self.scrollAreaContainerForm)

        self.retranslateUi(EnteteDetailWidget)
        QtCore.QMetaObject.connectSlotsByName(EnteteDetailWidget)

    def retranslateUi(self, EnteteDetailWidget):
        _translate = QtCore.QCoreApplication.translate
        EnteteDetailWidget.setWindowTitle(_translate("EnteteDetailWidget", "EnteteDetail"))
        self.pushButtonNouveau.setText(_translate("EnteteDetailWidget", "Nouveau"))
        self.pushButtonValider.setText(_translate("EnteteDetailWidget", "Valider"))
        self.pushButtonRechercher.setText(_translate("EnteteDetailWidget", "Rechercher"))
        self.pushButtonModifier.setText(_translate("EnteteDetailWidget", "Modifier"))
        self.pushButtonSupprimer.setText(_translate("EnteteDetailWidget", "Supprimer"))
        self.pushButtonPremier.setText(_translate("EnteteDetailWidget", "Premier"))
        self.pushButtonDernier.setText(_translate("EnteteDetailWidget", "Dernier"))
        self.pushButtonAvant.setText(_translate("EnteteDetailWidget", "Avant"))
        self.pushButtonArriere.setText(_translate("EnteteDetailWidget", "Arrierre"))
        self.pushButtonImprimer.setText(_translate("EnteteDetailWidget", "Imprimier"))
        self.pushButtonImprimerTout.setText(_translate("EnteteDetailWidget", "Imprimer tout"))
        self.pushButtonVisualiser.setText(_translate("EnteteDetailWidget", "Visualiser"))
        self.groupBoxEntete.setTitle(_translate("EnteteDetailWidget", "Entête"))
        self.labelCodeCmd.setText(_translate("EnteteDetailWidget", "code commande"))
        self.labelCodeFournisseur.setText(_translate("EnteteDetailWidget", "code fournisseur"))
        self.labelDateCmd.setText(_translate("EnteteDetailWidget", "date commande"))
        self.groupBoxDetail.setTitle(_translate("EnteteDetailWidget", "Detail"))
        self.labelPrixGlobal.setText(_translate("EnteteDetailWidget", "prix global"))
        item = self.tableWidgetDetailDisplay.horizontalHeaderItem(0)
        item.setText(_translate("EnteteDetailWidget", "Id commande"))
        item = self.tableWidgetDetailDisplay.horizontalHeaderItem(1)
        item.setText(_translate("EnteteDetailWidget", "Ref Produit"))
        item = self.tableWidgetDetailDisplay.horizontalHeaderItem(2)
        item.setText(_translate("EnteteDetailWidget", "Prix Unitaire"))
        item = self.tableWidgetDetailDisplay.horizontalHeaderItem(3)
        item.setText(_translate("EnteteDetailWidget", "Quantité"))
        item = self.tableWidgetDetailDisplay.horizontalHeaderItem(4)
        item.setText(_translate("EnteteDetailWidget", "Prix Global"))
        item = self.tableWidgetDetailDisplay.horizontalHeaderItem(5)
        item.setText(_translate("EnteteDetailWidget", "Date Livraison"))
        self.pushButtonSupprimerDetail.setText(_translate("EnteteDetailWidget", "Supprimer"))
        self.labelPrixUnitaire.setText(_translate("EnteteDetailWidget", "prix unitaire"))
        self.pushButtonInsererDetail.setText(_translate("EnteteDetailWidget", "Inserer"))
        self.pushButtonAjouterDetail.setText(_translate("EnteteDetailWidget", "Ajouter"))
        self.labelQuantite.setText(_translate("EnteteDetailWidget", "quantite"))
        self.labelIdCmd.setText(_translate("EnteteDetailWidget", "id commande"))
        self.pushButtonModifierDetail.setText(_translate("EnteteDetailWidget", "Modfier"))
        self.labelRefProduit.setText(_translate("EnteteDetailWidget", "ref produit"))
        self.labelDateLivraison.setText(_translate("EnteteDetailWidget", "date livraison"))
        self.pushButtonEffacerDetail.setText(_translate("EnteteDetailWidget", "Effacer"))
