# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FamilleProduitWidget1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FamilleProduitWidget(object):
    def setupUi(self, FamilleProduitWidget):
        FamilleProduitWidget.setObjectName("FamilleProduitWidget")
        FamilleProduitWidget.resize(676, 705)
        self.widgetCentral = QtWidgets.QWidget(FamilleProduitWidget)
        self.widgetCentral.setGeometry(QtCore.QRect(9, 9, 658, 687))
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widgetContainerButton = QtWidgets.QWidget(self.widgetCentral)
        self.widgetContainerButton.setMinimumSize(QtCore.QSize(93, 621))
        self.widgetContainerButton.setObjectName("widgetContainerButton")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetContainerButton)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonNouveau = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.verticalLayout.addWidget(self.pushButtonNouveau)
        self.pushButtonValider = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonValider.setObjectName("pushButtonValider")
        self.verticalLayout.addWidget(self.pushButtonValider)
        self.pushButtonRechercher = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonRechercher.setEnabled(False)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.verticalLayout.addWidget(self.pushButtonRechercher)
        self.pushButtonModifier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonModifier.setEnabled(False)
        self.pushButtonModifier.setObjectName("pushButtonModifier")
        self.verticalLayout.addWidget(self.pushButtonModifier)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonSupprimer.setEnabled(False)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.verticalLayout.addWidget(self.pushButtonSupprimer)
        self.pushButtonPremier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonPremier.setObjectName("pushButtonPremier")
        self.verticalLayout.addWidget(self.pushButtonPremier)
        self.pushButtonDernier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonDernier.setObjectName("pushButtonDernier")
        self.verticalLayout.addWidget(self.pushButtonDernier)
        self.pushButtonAvant = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonAvant.setEnabled(False)
        self.pushButtonAvant.setObjectName("pushButtonAvant")
        self.verticalLayout.addWidget(self.pushButtonAvant)
        self.pushButtonArriere = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonArriere.setEnabled(False)
        self.pushButtonArriere.setObjectName("pushButtonArriere")
        self.verticalLayout.addWidget(self.pushButtonArriere)
        self.pushButtonImprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimer.setEnabled(True)
        self.pushButtonImprimer.setObjectName("pushButtonImprimer")
        self.verticalLayout.addWidget(self.pushButtonImprimer)
        self.pushButtonImprimerTout = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimerTout.setEnabled(True)
        self.pushButtonImprimerTout.setObjectName("pushButtonImprimerTout")
        self.verticalLayout.addWidget(self.pushButtonImprimerTout)
        self.pushButtonVisualiser = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonVisualiser.setObjectName("pushButtonVisualiser")
        self.verticalLayout.addWidget(self.pushButtonVisualiser)
        spacerItem = QtWidgets.QSpacerItem(20, 314, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.widgetContainerButton)
        self.scrollAreaContainerForm = QtWidgets.QScrollArea(self.widgetCentral)
        self.scrollAreaContainerForm.setWidgetResizable(True)
        self.scrollAreaContainerForm.setObjectName("scrollAreaContainerForm")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 539, 667))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFamilleProduit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelFamilleProduit.setObjectName("labelFamilleProduit")
        self.horizontalLayout.addWidget(self.labelFamilleProduit)
        self.lineEdit_int_CodeFamilleProduit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_int_CodeFamilleProduit.setEnabled(False)
        self.lineEdit_int_CodeFamilleProduit.setObjectName("lineEdit_int_CodeFamilleProduit")
        self.horizontalLayout.addWidget(self.lineEdit_int_CodeFamilleProduit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelNomFamilleProduit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelNomFamilleProduit.setObjectName("labelNomFamilleProduit")
        self.horizontalLayout_2.addWidget(self.labelNomFamilleProduit)
        self.lineEdit_text_NomFamilleProduit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_text_NomFamilleProduit.setObjectName("lineEdit_text_NomFamilleProduit")
        self.horizontalLayout_2.addWidget(self.lineEdit_text_NomFamilleProduit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 590, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.scrollAreaContainerForm.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_6.addWidget(self.scrollAreaContainerForm)

        self.retranslateUi(FamilleProduitWidget)
        QtCore.QMetaObject.connectSlotsByName(FamilleProduitWidget)

    def retranslateUi(self, FamilleProduitWidget):
        _translate = QtCore.QCoreApplication.translate
        FamilleProduitWidget.setWindowTitle(_translate("FamilleProduitWidget", "FamilleProduitWidget"))
        self.pushButtonNouveau.setText(_translate("FamilleProduitWidget", "Nouveau"))
        self.pushButtonValider.setText(_translate("FamilleProduitWidget", "Valider"))
        self.pushButtonRechercher.setText(_translate("FamilleProduitWidget", "Rechercher"))
        self.pushButtonModifier.setText(_translate("FamilleProduitWidget", "Modifier"))
        self.pushButtonSupprimer.setText(_translate("FamilleProduitWidget", "Supprimer"))
        self.pushButtonPremier.setText(_translate("FamilleProduitWidget", "Premier"))
        self.pushButtonDernier.setText(_translate("FamilleProduitWidget", "Dernier"))
        self.pushButtonAvant.setText(_translate("FamilleProduitWidget", "Avant"))
        self.pushButtonArriere.setText(_translate("FamilleProduitWidget", "Arrierre"))
        self.pushButtonImprimer.setText(_translate("FamilleProduitWidget", "Imprimier"))
        self.pushButtonImprimerTout.setText(_translate("FamilleProduitWidget", "Imprimer tout"))
        self.pushButtonVisualiser.setText(_translate("FamilleProduitWidget", "Visualiser"))
        self.labelFamilleProduit.setText(_translate("FamilleProduitWidget", "code famille produit"))
        self.labelNomFamilleProduit.setText(_translate("FamilleProduitWidget", "Nom famille produit"))
