# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FournisseurWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fournisseurWidget(object):
    def setupUi(self, fournisseurWidget):
        fournisseurWidget.setObjectName("fournisseurWidget")
        fournisseurWidget.resize(694, 719)
        self.widgetCentral = QtWidgets.QWidget(fournisseurWidget)
        self.widgetCentral.setGeometry(QtCore.QRect(9, 9, 651, 698))
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widgetContainerButton = QtWidgets.QWidget(self.widgetCentral)
        self.widgetContainerButton.setMinimumSize(QtCore.QSize(93, 621))
        self.widgetContainerButton.setObjectName("widgetContainerButton")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetContainerButton)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonNouveau = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.verticalLayout.addWidget(self.pushButtonNouveau)
        self.pushButtonValider = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonValider.setObjectName("pushButtonValider")
        self.verticalLayout.addWidget(self.pushButtonValider)
        self.pushButtonRechercher = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonRechercher.setEnabled(False)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.verticalLayout.addWidget(self.pushButtonRechercher)
        self.pushButtonModifier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonModifier.setEnabled(False)
        self.pushButtonModifier.setObjectName("pushButtonModifier")
        self.verticalLayout.addWidget(self.pushButtonModifier)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonSupprimer.setEnabled(False)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.verticalLayout.addWidget(self.pushButtonSupprimer)
        self.pushButtonPremier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonPremier.setObjectName("pushButtonPremier")
        self.verticalLayout.addWidget(self.pushButtonPremier)
        self.pushButtonDernier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonDernier.setObjectName("pushButtonDernier")
        self.verticalLayout.addWidget(self.pushButtonDernier)
        self.pushButtonAvant = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonAvant.setEnabled(False)
        self.pushButtonAvant.setObjectName("pushButtonAvant")
        self.verticalLayout.addWidget(self.pushButtonAvant)
        self.pushButtonArriere = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonArriere.setEnabled(False)
        self.pushButtonArriere.setObjectName("pushButtonArriere")
        self.verticalLayout.addWidget(self.pushButtonArriere)
        self.pushButtonImprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimer.setEnabled(True)
        self.pushButtonImprimer.setObjectName("pushButtonImprimer")
        self.verticalLayout.addWidget(self.pushButtonImprimer)
        self.pushButtonImprimerTout = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimerTout.setEnabled(True)
        self.pushButtonImprimerTout.setObjectName("pushButtonImprimerTout")
        self.verticalLayout.addWidget(self.pushButtonImprimerTout)
        self.pushButtonVisualiser = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonVisualiser.setObjectName("pushButtonVisualiser")
        self.verticalLayout.addWidget(self.pushButtonVisualiser)
        spacerItem = QtWidgets.QSpacerItem(20, 314, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.widgetContainerButton)
        self.scrollAreaContainerForm = QtWidgets.QScrollArea(self.widgetCentral)
        self.scrollAreaContainerForm.setWidgetResizable(True)
        self.scrollAreaContainerForm.setObjectName("scrollAreaContainerForm")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 532, 678))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCodeFournisseuri = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelCodeFournisseuri.setMouseTracking(True)
        self.labelCodeFournisseuri.setObjectName("labelCodeFournisseuri")
        self.horizontalLayout.addWidget(self.labelCodeFournisseuri)
        self.lineEdit_int_CodeFourmisseuri = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_int_CodeFourmisseuri.setEnabled(False)
        self.lineEdit_int_CodeFourmisseuri.setObjectName("lineEdit_int_CodeFourmisseuri")
        self.horizontalLayout.addWidget(self.lineEdit_int_CodeFourmisseuri)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCodeFournisseur = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelCodeFournisseur.setMouseTracking(True)
        self.labelCodeFournisseur.setObjectName("labelCodeFournisseur")
        self.horizontalLayout_2.addWidget(self.labelCodeFournisseur)
        self.lineEdit_int_CodeFournisseur = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_int_CodeFournisseur.setObjectName("lineEdit_int_CodeFournisseur")
        self.horizontalLayout_2.addWidget(self.lineEdit_int_CodeFournisseur)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelNomFournisseur = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelNomFournisseur.setMouseTracking(True)
        self.labelNomFournisseur.setObjectName("labelNomFournisseur")
        self.horizontalLayout_3.addWidget(self.labelNomFournisseur)
        self.lineEdit_text_NomFournisseur = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_text_NomFournisseur.setObjectName("lineEdit_text_NomFournisseur")
        self.horizontalLayout_3.addWidget(self.lineEdit_text_NomFournisseur)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelTel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelTel.setMouseTracking(True)
        self.labelTel.setObjectName("labelTel")
        self.horizontalLayout_4.addWidget(self.labelTel)
        self.lineEdit_text_Tel = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_text_Tel.setObjectName("lineEdit_text_Tel")
        self.horizontalLayout_4.addWidget(self.lineEdit_text_Tel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelFax = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelFax.setMouseTracking(True)
        self.labelFax.setObjectName("labelFax")
        self.horizontalLayout_5.addWidget(self.labelFax)
        self.lineEdit_text_Fax = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_text_Fax.setObjectName("lineEdit_text_Fax")
        self.horizontalLayout_5.addWidget(self.lineEdit_text_Fax)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.scrollAreaContainerForm.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_6.addWidget(self.scrollAreaContainerForm)

        self.retranslateUi(fournisseurWidget)
        QtCore.QMetaObject.connectSlotsByName(fournisseurWidget)

    def retranslateUi(self, fournisseurWidget):
        _translate = QtCore.QCoreApplication.translate
        fournisseurWidget.setWindowTitle(_translate("fournisseurWidget", "fournisseurWidget"))
        self.pushButtonNouveau.setText(_translate("fournisseurWidget", "Nouveau"))
        self.pushButtonValider.setText(_translate("fournisseurWidget", "Valider"))
        self.pushButtonRechercher.setText(_translate("fournisseurWidget", "Rechercher"))
        self.pushButtonModifier.setText(_translate("fournisseurWidget", "Modifier"))
        self.pushButtonSupprimer.setText(_translate("fournisseurWidget", "Supprimer"))
        self.pushButtonPremier.setText(_translate("fournisseurWidget", "Premier"))
        self.pushButtonDernier.setText(_translate("fournisseurWidget", "Dernier"))
        self.pushButtonAvant.setText(_translate("fournisseurWidget", "Avant"))
        self.pushButtonArriere.setText(_translate("fournisseurWidget", "Arrierre"))
        self.pushButtonImprimer.setText(_translate("fournisseurWidget", "Imprimier"))
        self.pushButtonImprimerTout.setText(_translate("fournisseurWidget", "Imprimer tout"))
        self.pushButtonVisualiser.setText(_translate("fournisseurWidget", "Visualiser"))
        self.labelCodeFournisseuri.setText(_translate("fournisseurWidget", "code Fournisseuri"))
        self.labelCodeFournisseur.setText(_translate("fournisseurWidget", "code fournisseur"))
        self.labelNomFournisseur.setText(_translate("fournisseurWidget", "nom fournisseur"))
        self.labelTel.setText(_translate("fournisseurWidget", "tel"))
        self.labelFax.setText(_translate("fournisseurWidget", "fax"))
