# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProduitWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProduitWidget(object):
    def setupUi(self, ProduitWidget):
        ProduitWidget.setObjectName("ProduitWidget")
        ProduitWidget.resize(683, 657)
        self.widgetCentral = QtWidgets.QWidget(ProduitWidget)
        self.widgetCentral.setGeometry(QtCore.QRect(9, 9, 665, 639))
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widgetContainerButton = QtWidgets.QWidget(self.widgetCentral)
        self.widgetContainerButton.setMinimumSize(QtCore.QSize(93, 621))
        self.widgetContainerButton.setObjectName("widgetContainerButton")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetContainerButton)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonNouveau = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.verticalLayout.addWidget(self.pushButtonNouveau)
        self.pushButtonValider = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonValider.setObjectName("pushButtonValider")
        self.verticalLayout.addWidget(self.pushButtonValider)
        self.pushButtonRechercher = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonRechercher.setEnabled(False)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.verticalLayout.addWidget(self.pushButtonRechercher)
        self.pushButtonModifier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonModifier.setEnabled(False)
        self.pushButtonModifier.setObjectName("pushButtonModifier")
        self.verticalLayout.addWidget(self.pushButtonModifier)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonSupprimer.setEnabled(False)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.verticalLayout.addWidget(self.pushButtonSupprimer)
        self.pushButtonPremier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonPremier.setObjectName("pushButtonPremier")
        self.verticalLayout.addWidget(self.pushButtonPremier)
        self.pushButtonDernier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonDernier.setObjectName("pushButtonDernier")
        self.verticalLayout.addWidget(self.pushButtonDernier)
        self.pushButtonAvant = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonAvant.setEnabled(False)
        self.pushButtonAvant.setObjectName("pushButtonAvant")
        self.verticalLayout.addWidget(self.pushButtonAvant)
        self.pushButtonArriere = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonArriere.setEnabled(False)
        self.pushButtonArriere.setObjectName("pushButtonArriere")
        self.verticalLayout.addWidget(self.pushButtonArriere)
        self.pushButtonImprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimer.setEnabled(True)
        self.pushButtonImprimer.setObjectName("pushButtonImprimer")
        self.verticalLayout.addWidget(self.pushButtonImprimer)
        self.pushButtonImprimerTout = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimerTout.setEnabled(True)
        self.pushButtonImprimerTout.setObjectName("pushButtonImprimerTout")
        self.verticalLayout.addWidget(self.pushButtonImprimerTout)
        self.pushButtonVisualiser = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonVisualiser.setObjectName("pushButtonVisualiser")
        self.verticalLayout.addWidget(self.pushButtonVisualiser)
        spacerItem = QtWidgets.QSpacerItem(20, 314, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addWidget(self.widgetContainerButton)
        self.scrollAreaContainerForm = QtWidgets.QScrollArea(self.widgetCentral)
        self.scrollAreaContainerForm.setWidgetResizable(True)
        self.scrollAreaContainerForm.setObjectName("scrollAreaContainerForm")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 546, 619))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCodeProduit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelCodeProduit.setMouseTracking(True)
        self.labelCodeProduit.setObjectName("labelCodeProduit")
        self.horizontalLayout.addWidget(self.labelCodeProduit)
        self.lineEdit_int_CodeProduit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_int_CodeProduit.setEnabled(False)
        self.lineEdit_int_CodeProduit.setObjectName("lineEdit_int_CodeProduit")
        self.horizontalLayout.addWidget(self.lineEdit_int_CodeProduit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCodeFamilleProduit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelCodeFamilleProduit.setMouseTracking(True)
        self.labelCodeFamilleProduit.setObjectName("labelCodeFamilleProduit")
        self.horizontalLayout_2.addWidget(self.labelCodeFamilleProduit)
        self.comboBoxCodeFamilleProduit = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxCodeFamilleProduit.setMinimumSize(QtCore.QSize(131, 20))
        self.comboBoxCodeFamilleProduit.setObjectName("comboBoxCodeFamilleProduit")
        self.comboBoxCodeFamilleProduit.addItem("")
        self.comboBoxCodeFamilleProduit.addItem("")
        self.comboBoxCodeFamilleProduit.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxCodeFamilleProduit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelNomProduit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelNomProduit.setMouseTracking(True)
        self.labelNomProduit.setObjectName("labelNomProduit")
        self.horizontalLayout_3.addWidget(self.labelNomProduit)
        self.lineEdit_text_NomProduit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_text_NomProduit.setObjectName("lineEdit_text_NomProduit")
        self.horizontalLayout_3.addWidget(self.lineEdit_text_NomProduit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.scrollAreaContainerForm.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollAreaContainerForm)

        self.retranslateUi(ProduitWidget)
        QtCore.QMetaObject.connectSlotsByName(ProduitWidget)

    def retranslateUi(self, ProduitWidget):
        _translate = QtCore.QCoreApplication.translate
        ProduitWidget.setWindowTitle(_translate("ProduitWidget", "Form"))
        self.pushButtonNouveau.setText(_translate("ProduitWidget", "Nouveau"))
        self.pushButtonValider.setText(_translate("ProduitWidget", "Valider"))
        self.pushButtonRechercher.setText(_translate("ProduitWidget", "Rechercher"))
        self.pushButtonModifier.setText(_translate("ProduitWidget", "Modifier"))
        self.pushButtonSupprimer.setText(_translate("ProduitWidget", "Supprimer"))
        self.pushButtonPremier.setText(_translate("ProduitWidget", "Premier"))
        self.pushButtonDernier.setText(_translate("ProduitWidget", "Dernier"))
        self.pushButtonAvant.setText(_translate("ProduitWidget", "Avant"))
        self.pushButtonArriere.setText(_translate("ProduitWidget", "Arrierre"))
        self.pushButtonImprimer.setText(_translate("ProduitWidget", "Imprimier"))
        self.pushButtonImprimerTout.setText(_translate("ProduitWidget", "Imprimer tout"))
        self.pushButtonVisualiser.setText(_translate("ProduitWidget", "Visualiser"))
        self.labelCodeProduit.setText(_translate("ProduitWidget", "code produit"))
        self.labelCodeFamilleProduit.setText(_translate("ProduitWidget", "code famille produit"))
        self.comboBoxCodeFamilleProduit.setItemText(0, _translate("ProduitWidget", "role1"))
        self.comboBoxCodeFamilleProduit.setItemText(1, _translate("ProduitWidget", "role2"))
        self.comboBoxCodeFamilleProduit.setItemText(2, _translate("ProduitWidget", "role3"))
        self.labelNomProduit.setText(_translate("ProduitWidget", "nom produit"))
