# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\COZMET\Desktop\todoPyQt\FounisseurSupprimerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FournisseurSupprimerWidget(object):
    def setupUi(self, FournisseurSupprimerWidget):
        FournisseurSupprimerWidget.setObjectName("FournisseurSupprimerWidget")
        FournisseurSupprimerWidget.resize(687, 585)
        self.verticalLayout = QtWidgets.QVBoxLayout(FournisseurSupprimerWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditCle = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditCle.setObjectName("lineEditCle")
        self.horizontalLayout.addWidget(self.lineEditCle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonRechercher = QtWidgets.QPushButton(FournisseurSupprimerWidget)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.horizontalLayout_2.addWidget(self.pushButtonRechercher)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelEmail = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.labelEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 8, 1, 1, 1)
        self.lineEditFichier = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditFichier.setEnabled(False)
        self.lineEditFichier.setInputMask("")
        self.lineEditFichier.setFrame(True)
        self.lineEditFichier.setDragEnabled(False)
        self.lineEditFichier.setReadOnly(False)
        self.lineEditFichier.setClearButtonEnabled(False)
        self.lineEditFichier.setObjectName("lineEditFichier")
        self.gridLayout.addWidget(self.lineEditFichier, 9, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 11, 1, 1, 1)
        self.lineEditCodeFounisseur = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditCodeFounisseur.setEnabled(False)
        self.lineEditCodeFounisseur.setInputMask("")
        self.lineEditCodeFounisseur.setFrame(True)
        self.lineEditCodeFounisseur.setDragEnabled(False)
        self.lineEditCodeFounisseur.setReadOnly(False)
        self.lineEditCodeFounisseur.setClearButtonEnabled(False)
        self.lineEditCodeFounisseur.setObjectName("lineEditCodeFounisseur")
        self.gridLayout.addWidget(self.lineEditCodeFounisseur, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 15, 1, 1, 1)
        self.lineEditAdresse = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditAdresse.setEnabled(False)
        self.lineEditAdresse.setInputMask("")
        self.lineEditAdresse.setFrame(True)
        self.lineEditAdresse.setDragEnabled(False)
        self.lineEditAdresse.setReadOnly(False)
        self.lineEditAdresse.setClearButtonEnabled(False)
        self.lineEditAdresse.setObjectName("lineEditAdresse")
        self.gridLayout.addWidget(self.lineEditAdresse, 13, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.lineEditTelephone = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditTelephone.setEnabled(False)
        self.lineEditTelephone.setInputMask("")
        self.lineEditTelephone.setFrame(True)
        self.lineEditTelephone.setDragEnabled(False)
        self.lineEditTelephone.setReadOnly(False)
        self.lineEditTelephone.setClearButtonEnabled(False)
        self.lineEditTelephone.setObjectName("lineEditTelephone")
        self.gridLayout.addWidget(self.lineEditTelephone, 4, 2, 1, 1)
        self.lineEditCompteB = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditCompteB.setEnabled(False)
        self.lineEditCompteB.setInputMask("")
        self.lineEditCompteB.setFrame(True)
        self.lineEditCompteB.setDragEnabled(False)
        self.lineEditCompteB.setReadOnly(False)
        self.lineEditCompteB.setClearButtonEnabled(False)
        self.lineEditCompteB.setObjectName("lineEditCompteB")
        self.gridLayout.addWidget(self.lineEditCompteB, 11, 2, 1, 1)
        self.lineEditAdresseFournisseur = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditAdresseFournisseur.setEnabled(False)
        self.lineEditAdresseFournisseur.setInputMask("")
        self.lineEditAdresseFournisseur.setFrame(True)
        self.lineEditAdresseFournisseur.setDragEnabled(False)
        self.lineEditAdresseFournisseur.setReadOnly(False)
        self.lineEditAdresseFournisseur.setClearButtonEnabled(False)
        self.lineEditAdresseFournisseur.setObjectName("lineEditAdresseFournisseur")
        self.gridLayout.addWidget(self.lineEditAdresseFournisseur, 12, 2, 1, 1)
        self.lineEditFlag = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditFlag.setEnabled(False)
        self.lineEditFlag.setInputMask("")
        self.lineEditFlag.setFrame(True)
        self.lineEditFlag.setDragEnabled(False)
        self.lineEditFlag.setReadOnly(False)
        self.lineEditFlag.setClearButtonEnabled(False)
        self.lineEditFlag.setObjectName("lineEditFlag")
        self.gridLayout.addWidget(self.lineEditFlag, 17, 2, 1, 1)
        self.lineEditCorespondance = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditCorespondance.setEnabled(False)
        self.lineEditCorespondance.setInputMask("")
        self.lineEditCorespondance.setFrame(True)
        self.lineEditCorespondance.setDragEnabled(False)
        self.lineEditCorespondance.setReadOnly(False)
        self.lineEditCorespondance.setClearButtonEnabled(False)
        self.lineEditCorespondance.setObjectName("lineEditCorespondance")
        self.gridLayout.addWidget(self.lineEditCorespondance, 6, 2, 1, 1)
        self.labelSiteWeb = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.labelSiteWeb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSiteWeb.setObjectName("labelSiteWeb")
        self.gridLayout.addWidget(self.labelSiteWeb, 7, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 3, 1, 1)
        self.lineEditSiteWeb = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditSiteWeb.setEnabled(False)
        self.lineEditSiteWeb.setInputMask("")
        self.lineEditSiteWeb.setFrame(True)
        self.lineEditSiteWeb.setDragEnabled(False)
        self.lineEditSiteWeb.setReadOnly(False)
        self.lineEditSiteWeb.setClearButtonEnabled(False)
        self.lineEditSiteWeb.setObjectName("lineEditSiteWeb")
        self.gridLayout.addWidget(self.lineEditSiteWeb, 7, 2, 1, 1)
        self.labelCorespondance = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.labelCorespondance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCorespondance.setObjectName("labelCorespondance")
        self.gridLayout.addWidget(self.labelCorespondance, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 12, 1, 1, 1)
        self.lineEditRegistreCommerce = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditRegistreCommerce.setEnabled(False)
        self.lineEditRegistreCommerce.setInputMask("")
        self.lineEditRegistreCommerce.setFrame(True)
        self.lineEditRegistreCommerce.setDragEnabled(False)
        self.lineEditRegistreCommerce.setReadOnly(False)
        self.lineEditRegistreCommerce.setClearButtonEnabled(False)
        self.lineEditRegistreCommerce.setObjectName("lineEditRegistreCommerce")
        self.gridLayout.addWidget(self.lineEditRegistreCommerce, 3, 2, 1, 1)
        self.lineEditFax = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditFax.setEnabled(False)
        self.lineEditFax.setInputMask("")
        self.lineEditFax.setFrame(True)
        self.lineEditFax.setDragEnabled(False)
        self.lineEditFax.setReadOnly(False)
        self.lineEditFax.setClearButtonEnabled(False)
        self.lineEditFax.setObjectName("lineEditFax")
        self.gridLayout.addWidget(self.lineEditFax, 5, 2, 1, 1)
        self.lineEditAdresseBanque = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditAdresseBanque.setEnabled(False)
        self.lineEditAdresseBanque.setInputMask("")
        self.lineEditAdresseBanque.setFrame(True)
        self.lineEditAdresseBanque.setDragEnabled(False)
        self.lineEditAdresseBanque.setReadOnly(False)
        self.lineEditAdresseBanque.setClearButtonEnabled(False)
        self.lineEditAdresseBanque.setObjectName("lineEditAdresseBanque")
        self.gridLayout.addWidget(self.lineEditAdresseBanque, 10, 2, 1, 1)
        self.lineEditNomFournisseur = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditNomFournisseur.setEnabled(False)
        self.lineEditNomFournisseur.setInputMask("")
        self.lineEditNomFournisseur.setFrame(True)
        self.lineEditNomFournisseur.setDragEnabled(False)
        self.lineEditNomFournisseur.setReadOnly(False)
        self.lineEditNomFournisseur.setClearButtonEnabled(False)
        self.lineEditNomFournisseur.setObjectName("lineEditNomFournisseur")
        self.gridLayout.addWidget(self.lineEditNomFournisseur, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 13, 1, 1, 1)
        self.labelFax = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.labelFax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFax.setObjectName("labelFax")
        self.gridLayout.addWidget(self.labelFax, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 1, 1, 1)
        self.labelRegistreCommerce = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.labelRegistreCommerce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRegistreCommerce.setObjectName("labelRegistreCommerce")
        self.gridLayout.addWidget(self.labelRegistreCommerce, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 14, 1, 1, 1)
        self.labelTelephone = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.labelTelephone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTelephone.setObjectName("labelTelephone")
        self.gridLayout.addWidget(self.labelTelephone, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 17, 1, 1, 1)
        self.lineEditAdresse1 = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditAdresse1.setEnabled(False)
        self.lineEditAdresse1.setInputMask("")
        self.lineEditAdresse1.setFrame(True)
        self.lineEditAdresse1.setDragEnabled(False)
        self.lineEditAdresse1.setReadOnly(False)
        self.lineEditAdresse1.setClearButtonEnabled(False)
        self.lineEditAdresse1.setObjectName("lineEditAdresse1")
        self.gridLayout.addWidget(self.lineEditAdresse1, 14, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 1, 1, 1)
        self.lineEditCodeFournisseuri = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditCodeFournisseuri.setEnabled(False)
        self.lineEditCodeFournisseuri.setInputMask("")
        self.lineEditCodeFournisseuri.setFrame(True)
        self.lineEditCodeFournisseuri.setDragEnabled(False)
        self.lineEditCodeFournisseuri.setReadOnly(False)
        self.lineEditCodeFournisseuri.setClearButtonEnabled(False)
        self.lineEditCodeFournisseuri.setObjectName("lineEditCodeFournisseuri")
        self.gridLayout.addWidget(self.lineEditCodeFournisseuri, 0, 2, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditEmail.setEnabled(False)
        self.lineEditEmail.setInputMask("")
        self.lineEditEmail.setFrame(True)
        self.lineEditEmail.setDragEnabled(False)
        self.lineEditEmail.setReadOnly(False)
        self.lineEditEmail.setClearButtonEnabled(False)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.gridLayout.addWidget(self.lineEditEmail, 8, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 16, 1, 1, 1)
        self.lineEditRemarque2 = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditRemarque2.setEnabled(False)
        self.lineEditRemarque2.setInputMask("")
        self.lineEditRemarque2.setFrame(True)
        self.lineEditRemarque2.setDragEnabled(False)
        self.lineEditRemarque2.setReadOnly(False)
        self.lineEditRemarque2.setClearButtonEnabled(False)
        self.lineEditRemarque2.setObjectName("lineEditRemarque2")
        self.gridLayout.addWidget(self.lineEditRemarque2, 16, 2, 1, 1)
        self.lineEditRemarque1 = QtWidgets.QLineEdit(FournisseurSupprimerWidget)
        self.lineEditRemarque1.setEnabled(False)
        self.lineEditRemarque1.setInputMask("")
        self.lineEditRemarque1.setFrame(True)
        self.lineEditRemarque1.setDragEnabled(False)
        self.lineEditRemarque1.setReadOnly(False)
        self.lineEditRemarque1.setClearButtonEnabled(False)
        self.lineEditRemarque1.setObjectName("lineEditRemarque1")
        self.gridLayout.addWidget(self.lineEditRemarque1, 15, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(FournisseurSupprimerWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButtonSupprimer = QtWidgets.QPushButton(FournisseurSupprimerWidget)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.horizontalLayout_3.addWidget(self.pushButtonSupprimer)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(FournisseurSupprimerWidget)
        QtCore.QMetaObject.connectSlotsByName(FournisseurSupprimerWidget)

    def retranslateUi(self, FournisseurSupprimerWidget):
        _translate = QtCore.QCoreApplication.translate
        FournisseurSupprimerWidget.setWindowTitle(_translate("FournisseurSupprimerWidget", "FounisseurSupprimerWidget"))
        self.label.setText(_translate("FournisseurSupprimerWidget", "Rechercher pour supprimer"))
        self.pushButtonRechercher.setText(_translate("FournisseurSupprimerWidget", "Rechercher"))
        self.labelEmail.setText(_translate("FournisseurSupprimerWidget", "Email"))
        self.label_17.setText(_translate("FournisseurSupprimerWidget", "Compte B"))
        self.label_12.setText(_translate("FournisseurSupprimerWidget", "Remarque 1"))
        self.label_4.setText(_translate("FournisseurSupprimerWidget", "Code Fourisseur"))
        self.labelSiteWeb.setText(_translate("FournisseurSupprimerWidget", "Site Web"))
        self.labelCorespondance.setText(_translate("FournisseurSupprimerWidget", "C Corespandance"))
        self.label_3.setText(_translate("FournisseurSupprimerWidget", "Nom Fournisseur"))
        self.label_18.setText(_translate("FournisseurSupprimerWidget", "Adresse Fournisseur"))
        self.label_16.setText(_translate("FournisseurSupprimerWidget", "Adresse"))
        self.labelFax.setText(_translate("FournisseurSupprimerWidget", "Fax"))
        self.label_15.setText(_translate("FournisseurSupprimerWidget", "Adresse Banque"))
        self.labelRegistreCommerce.setText(_translate("FournisseurSupprimerWidget", "Registre de commerce"))
        self.label_14.setText(_translate("FournisseurSupprimerWidget", "Adresse 1"))
        self.labelTelephone.setText(_translate("FournisseurSupprimerWidget", "Telephone"))
        self.label_10.setText(_translate("FournisseurSupprimerWidget", "Flag"))
        self.label_13.setText(_translate("FournisseurSupprimerWidget", "Fichier"))
        self.label_11.setText(_translate("FournisseurSupprimerWidget", "Remarque 2"))
        self.label_2.setText(_translate("FournisseurSupprimerWidget", "Code Fournisseuri"))
        self.pushButtonSupprimer.setText(_translate("FournisseurSupprimerWidget", "Supprimer !"))
