# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\COZMET\Desktop\todoPyQt\FournisseurDefilerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FournisseurDefilerWidget(object):
    def setupUi(self, FournisseurDefilerWidget):
        FournisseurDefilerWidget.setObjectName("FournisseurDefilerWidget")
        FournisseurDefilerWidget.resize(600, 538)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FournisseurDefilerWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelSiteWeb = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.labelSiteWeb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSiteWeb.setObjectName("labelSiteWeb")
        self.gridLayout.addWidget(self.labelSiteWeb, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 14, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 11, 1, 1, 1)
        self.lineEditFlag = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditFlag.setEnabled(False)
        self.lineEditFlag.setObjectName("lineEditFlag")
        self.gridLayout.addWidget(self.lineEditFlag, 17, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 17, 1, 1, 1)
        self.lineEditFax = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditFax.setEnabled(False)
        self.lineEditFax.setObjectName("lineEditFax")
        self.gridLayout.addWidget(self.lineEditFax, 5, 2, 1, 1)
        self.lineEditAdresseFournisseur = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditAdresseFournisseur.setEnabled(False)
        self.lineEditAdresseFournisseur.setObjectName("lineEditAdresseFournisseur")
        self.gridLayout.addWidget(self.lineEditAdresseFournisseur, 12, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.lineEditFichier = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditFichier.setEnabled(False)
        self.lineEditFichier.setObjectName("lineEditFichier")
        self.gridLayout.addWidget(self.lineEditFichier, 9, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.lineEditSiteWeb = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditSiteWeb.setEnabled(False)
        self.lineEditSiteWeb.setObjectName("lineEditSiteWeb")
        self.gridLayout.addWidget(self.lineEditSiteWeb, 7, 2, 1, 1)
        self.lineEditCodeFournisseuri = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditCodeFournisseuri.setEnabled(False)
        self.lineEditCodeFournisseuri.setObjectName("lineEditCodeFournisseuri")
        self.gridLayout.addWidget(self.lineEditCodeFournisseuri, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 13, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 16, 1, 1, 1)
        self.lineEditAdresse1 = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditAdresse1.setEnabled(False)
        self.lineEditAdresse1.setObjectName("lineEditAdresse1")
        self.gridLayout.addWidget(self.lineEditAdresse1, 14, 2, 1, 1)
        self.lineEditCompteB = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditCompteB.setEnabled(False)
        self.lineEditCompteB.setObjectName("lineEditCompteB")
        self.gridLayout.addWidget(self.lineEditCompteB, 11, 2, 1, 1)
        self.labelTelephone = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.labelTelephone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTelephone.setObjectName("labelTelephone")
        self.gridLayout.addWidget(self.labelTelephone, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.lineEditCodeFounisseur = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditCodeFounisseur.setEnabled(False)
        self.lineEditCodeFounisseur.setObjectName("lineEditCodeFounisseur")
        self.gridLayout.addWidget(self.lineEditCodeFounisseur, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 15, 1, 1, 1)
        self.labelCorespondance = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.labelCorespondance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCorespondance.setObjectName("labelCorespondance")
        self.gridLayout.addWidget(self.labelCorespondance, 6, 1, 1, 1)
        self.lineEditAdresse = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditAdresse.setEnabled(False)
        self.lineEditAdresse.setObjectName("lineEditAdresse")
        self.gridLayout.addWidget(self.lineEditAdresse, 13, 2, 1, 1)
        self.labelRegistreCommerce = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.labelRegistreCommerce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRegistreCommerce.setObjectName("labelRegistreCommerce")
        self.gridLayout.addWidget(self.labelRegistreCommerce, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 1, 1, 1)
        self.labelEmail = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.labelEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 8, 1, 1, 1)
        self.lineEditRemarque2 = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditRemarque2.setEnabled(False)
        self.lineEditRemarque2.setObjectName("lineEditRemarque2")
        self.gridLayout.addWidget(self.lineEditRemarque2, 16, 2, 1, 1)
        self.lineEditTelephone = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditTelephone.setEnabled(False)
        self.lineEditTelephone.setObjectName("lineEditTelephone")
        self.gridLayout.addWidget(self.lineEditTelephone, 4, 2, 1, 1)
        self.lineEditNomFournisseur = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditNomFournisseur.setEnabled(False)
        self.lineEditNomFournisseur.setObjectName("lineEditNomFournisseur")
        self.gridLayout.addWidget(self.lineEditNomFournisseur, 1, 2, 1, 1)
        self.lineEditRemarque1 = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditRemarque1.setEnabled(False)
        self.lineEditRemarque1.setObjectName("lineEditRemarque1")
        self.gridLayout.addWidget(self.lineEditRemarque1, 15, 2, 1, 1)
        self.labelFax = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.labelFax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFax.setObjectName("labelFax")
        self.gridLayout.addWidget(self.labelFax, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 12, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 1, 1, 1)
        self.lineEditCorespondance = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditCorespondance.setEnabled(False)
        self.lineEditCorespondance.setObjectName("lineEditCorespondance")
        self.gridLayout.addWidget(self.lineEditCorespondance, 6, 2, 1, 1)
        self.lineEditRegistreCommerce = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditRegistreCommerce.setEnabled(False)
        self.lineEditRegistreCommerce.setObjectName("lineEditRegistreCommerce")
        self.gridLayout.addWidget(self.lineEditRegistreCommerce, 3, 2, 1, 1)
        self.lineEditAdresseBanque = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditAdresseBanque.setEnabled(False)
        self.lineEditAdresseBanque.setObjectName("lineEditAdresseBanque")
        self.gridLayout.addWidget(self.lineEditAdresseBanque, 10, 2, 1, 1)
        self.label = QtWidgets.QLabel(FournisseurDefilerWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(FournisseurDefilerWidget)
        self.lineEditEmail.setEnabled(False)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.gridLayout.addWidget(self.lineEditEmail, 8, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonModifer = QtWidgets.QPushButton(FournisseurDefilerWidget)
        self.pushButtonModifer.setObjectName("pushButtonModifer")
        self.horizontalLayout.addWidget(self.pushButtonModifer)
        self.pushButtonSupprimer = QtWidgets.QPushButton(FournisseurDefilerWidget)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.horizontalLayout.addWidget(self.pushButtonSupprimer)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(FournisseurDefilerWidget)
        QtCore.QMetaObject.connectSlotsByName(FournisseurDefilerWidget)

    def retranslateUi(self, FournisseurDefilerWidget):
        _translate = QtCore.QCoreApplication.translate
        FournisseurDefilerWidget.setWindowTitle(_translate("FournisseurDefilerWidget", "FounisseurDefilerWidget"))
        self.labelSiteWeb.setText(_translate("FournisseurDefilerWidget", "Site Web"))
        self.label_14.setText(_translate("FournisseurDefilerWidget", "Adresse 1"))
        self.label_17.setText(_translate("FournisseurDefilerWidget", "Compte B"))
        self.label_10.setText(_translate("FournisseurDefilerWidget", "Flag"))
        self.label_3.setText(_translate("FournisseurDefilerWidget", "Code Fourisseur"))
        self.label_16.setText(_translate("FournisseurDefilerWidget", "Adresse"))
        self.label_11.setText(_translate("FournisseurDefilerWidget", "Remarque 2"))
        self.labelTelephone.setText(_translate("FournisseurDefilerWidget", "Telephone"))
        self.label_2.setText(_translate("FournisseurDefilerWidget", "Nom Fournisseur"))
        self.label_12.setText(_translate("FournisseurDefilerWidget", "Remarque 1"))
        self.labelCorespondance.setText(_translate("FournisseurDefilerWidget", "C Corespandance"))
        self.labelRegistreCommerce.setText(_translate("FournisseurDefilerWidget", "Registre de commerce"))
        self.label_15.setText(_translate("FournisseurDefilerWidget", "Adresse Banque"))
        self.labelEmail.setText(_translate("FournisseurDefilerWidget", "Email"))
        self.labelFax.setText(_translate("FournisseurDefilerWidget", "Fax"))
        self.label_18.setText(_translate("FournisseurDefilerWidget", "Adresse Fournisseur"))
        self.label_13.setText(_translate("FournisseurDefilerWidget", "Fichier"))
        self.label.setText(_translate("FournisseurDefilerWidget", "Code Fournisseuri"))
        self.pushButtonModifer.setText(_translate("FournisseurDefilerWidget", "Modifier"))
        self.pushButtonSupprimer.setText(_translate("FournisseurDefilerWidget", "Supprimer"))
