# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\COZMET\Desktop\todoPyQt\FournisseurValideWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FounisseurValideWidget(object):
    def setupUi(self, FounisseurValideWidget):
        FounisseurValideWidget.setObjectName("FounisseurValideWidget")
        FounisseurValideWidget.resize(251, 472)
        self.layoutWidget = QtWidgets.QWidget(FounisseurValideWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 247, 464))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditCodeFournisseuri = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditCodeFournisseuri.setObjectName("lineEditCodeFournisseuri")
        self.gridLayout.addWidget(self.lineEditCodeFournisseuri, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditNomFournisseur = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNomFournisseur.setObjectName("lineEditNomFournisseur")
        self.gridLayout.addWidget(self.lineEditNomFournisseur, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditCodeFounisseur = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditCodeFounisseur.setObjectName("lineEditCodeFounisseur")
        self.gridLayout.addWidget(self.lineEditCodeFounisseur, 2, 1, 1, 1)
        self.labelRegistreCommerce = QtWidgets.QLabel(self.layoutWidget)
        self.labelRegistreCommerce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRegistreCommerce.setObjectName("labelRegistreCommerce")
        self.gridLayout.addWidget(self.labelRegistreCommerce, 3, 0, 1, 1)
        self.lineEditRegistreCommerce = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditRegistreCommerce.setObjectName("lineEditRegistreCommerce")
        self.gridLayout.addWidget(self.lineEditRegistreCommerce, 3, 1, 1, 1)
        self.labelTelephone = QtWidgets.QLabel(self.layoutWidget)
        self.labelTelephone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTelephone.setObjectName("labelTelephone")
        self.gridLayout.addWidget(self.labelTelephone, 4, 0, 1, 1)
        self.lineEditTelephone = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTelephone.setObjectName("lineEditTelephone")
        self.gridLayout.addWidget(self.lineEditTelephone, 4, 1, 1, 1)
        self.labelFax = QtWidgets.QLabel(self.layoutWidget)
        self.labelFax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFax.setObjectName("labelFax")
        self.gridLayout.addWidget(self.labelFax, 5, 0, 1, 1)
        self.lineEditFax = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFax.setObjectName("lineEditFax")
        self.gridLayout.addWidget(self.lineEditFax, 5, 1, 1, 1)
        self.labelCorespondance = QtWidgets.QLabel(self.layoutWidget)
        self.labelCorespondance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCorespondance.setObjectName("labelCorespondance")
        self.gridLayout.addWidget(self.labelCorespondance, 6, 0, 1, 1)
        self.lineEditCorespondance = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditCorespondance.setObjectName("lineEditCorespondance")
        self.gridLayout.addWidget(self.lineEditCorespondance, 6, 1, 1, 1)
        self.labelSiteWeb = QtWidgets.QLabel(self.layoutWidget)
        self.labelSiteWeb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSiteWeb.setObjectName("labelSiteWeb")
        self.gridLayout.addWidget(self.labelSiteWeb, 7, 0, 1, 1)
        self.lineEditSiteWeb = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditSiteWeb.setObjectName("lineEditSiteWeb")
        self.gridLayout.addWidget(self.lineEditSiteWeb, 7, 1, 1, 1)
        self.labelEmail = QtWidgets.QLabel(self.layoutWidget)
        self.labelEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 8, 0, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.gridLayout.addWidget(self.lineEditEmail, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.lineEditFichier = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFichier.setObjectName("lineEditFichier")
        self.gridLayout.addWidget(self.lineEditFichier, 9, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 0, 1, 1)
        self.lineEditAdresseBanque = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditAdresseBanque.setObjectName("lineEditAdresseBanque")
        self.gridLayout.addWidget(self.lineEditAdresseBanque, 10, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 11, 0, 1, 1)
        self.lineEditCompteB = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditCompteB.setObjectName("lineEditCompteB")
        self.gridLayout.addWidget(self.lineEditCompteB, 11, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 12, 0, 1, 1)
        self.lineEditAdresseFournisseur = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditAdresseFournisseur.setObjectName("lineEditAdresseFournisseur")
        self.gridLayout.addWidget(self.lineEditAdresseFournisseur, 12, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 13, 0, 1, 1)
        self.lineEditAdresse = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditAdresse.setObjectName("lineEditAdresse")
        self.gridLayout.addWidget(self.lineEditAdresse, 13, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 14, 0, 1, 1)
        self.lineEditAdresse1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditAdresse1.setObjectName("lineEditAdresse1")
        self.gridLayout.addWidget(self.lineEditAdresse1, 14, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 15, 0, 1, 1)
        self.lineEditRemarque1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditRemarque1.setObjectName("lineEditRemarque1")
        self.gridLayout.addWidget(self.lineEditRemarque1, 15, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 16, 0, 1, 1)
        self.lineEditRemarque2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditRemarque2.setObjectName("lineEditRemarque2")
        self.gridLayout.addWidget(self.lineEditRemarque2, 16, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 17, 0, 1, 1)
        self.lineEditFlag = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFlag.setObjectName("lineEditFlag")
        self.gridLayout.addWidget(self.lineEditFlag, 17, 1, 1, 1)

        self.retranslateUi(FounisseurValideWidget)
        QtCore.QMetaObject.connectSlotsByName(FounisseurValideWidget)

    def retranslateUi(self, FounisseurValideWidget):
        _translate = QtCore.QCoreApplication.translate
        FounisseurValideWidget.setWindowTitle(_translate("FounisseurValideWidget", "Fournisseur"))
        self.label.setText(_translate("FounisseurValideWidget", "Code Fournisseuri"))
        self.label_2.setText(_translate("FounisseurValideWidget", "Nom Fournisseur"))
        self.label_3.setText(_translate("FounisseurValideWidget", "Code Fourisseur"))
        self.labelRegistreCommerce.setText(_translate("FounisseurValideWidget", "Registre de commerce"))
        self.labelTelephone.setText(_translate("FounisseurValideWidget", "Telephone"))
        self.labelFax.setText(_translate("FounisseurValideWidget", "Fax"))
        self.labelCorespondance.setText(_translate("FounisseurValideWidget", "C Corespandance"))
        self.labelSiteWeb.setText(_translate("FounisseurValideWidget", "Site Web"))
        self.labelEmail.setText(_translate("FounisseurValideWidget", "Email"))
        self.label_13.setText(_translate("FounisseurValideWidget", "Fichier"))
        self.label_15.setText(_translate("FounisseurValideWidget", "Adresse Banque"))
        self.label_17.setText(_translate("FounisseurValideWidget", "Compte B"))
        self.label_18.setText(_translate("FounisseurValideWidget", "Adresse Fournisseur"))
        self.label_16.setText(_translate("FounisseurValideWidget", "Adresse"))
        self.label_14.setText(_translate("FounisseurValideWidget", "Adresse 1"))
        self.label_12.setText(_translate("FounisseurValideWidget", "Remarque 1"))
        self.label_11.setText(_translate("FounisseurValideWidget", "Remarque 2"))
        self.label_10.setText(_translate("FounisseurValideWidget", "Flag"))
