# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\COZMET\Desktop\todoPyQt\FournisseurModifierWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FounisseurModificationWidget(object):
    def setupUi(self, FounisseurModificationWidget):
        FounisseurModificationWidget.setObjectName("FounisseurModificationWidget")
        FounisseurModificationWidget.resize(687, 585)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FounisseurModificationWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditCle = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditCle.setObjectName("lineEditCle")
        self.horizontalLayout.addWidget(self.lineEditCle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonRechercher = QtWidgets.QPushButton(FounisseurModificationWidget)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.horizontalLayout_2.addWidget(self.pushButtonRechercher)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelEmail = QtWidgets.QLabel(FounisseurModificationWidget)
        self.labelEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout.addWidget(self.labelEmail, 8, 1, 1, 1)
        self.lineEditFichier = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditFichier.setObjectName("lineEditFichier")
        self.gridLayout.addWidget(self.lineEditFichier, 9, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 11, 1, 1, 1)
        self.lineEditCodeFounisseur = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditCodeFounisseur.setObjectName("lineEditCodeFounisseur")
        self.gridLayout.addWidget(self.lineEditCodeFounisseur, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 15, 1, 1, 1)
        self.lineEditAdresse = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditAdresse.setObjectName("lineEditAdresse")
        self.gridLayout.addWidget(self.lineEditAdresse, 13, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.lineEditTelephone = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditTelephone.setObjectName("lineEditTelephone")
        self.gridLayout.addWidget(self.lineEditTelephone, 4, 2, 1, 1)
        self.lineEditCompteB = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditCompteB.setObjectName("lineEditCompteB")
        self.gridLayout.addWidget(self.lineEditCompteB, 11, 2, 1, 1)
        self.lineEditAdresseFournisseur = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditAdresseFournisseur.setObjectName("lineEditAdresseFournisseur")
        self.gridLayout.addWidget(self.lineEditAdresseFournisseur, 12, 2, 1, 1)
        self.lineEditFlag = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditFlag.setObjectName("lineEditFlag")
        self.gridLayout.addWidget(self.lineEditFlag, 17, 2, 1, 1)
        self.lineEditCorespondance = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditCorespondance.setObjectName("lineEditCorespondance")
        self.gridLayout.addWidget(self.lineEditCorespondance, 6, 2, 1, 1)
        self.labelSiteWeb = QtWidgets.QLabel(FounisseurModificationWidget)
        self.labelSiteWeb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSiteWeb.setObjectName("labelSiteWeb")
        self.gridLayout.addWidget(self.labelSiteWeb, 7, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 3, 1, 1)
        self.lineEditSiteWeb = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditSiteWeb.setObjectName("lineEditSiteWeb")
        self.gridLayout.addWidget(self.lineEditSiteWeb, 7, 2, 1, 1)
        self.labelCorespondance = QtWidgets.QLabel(FounisseurModificationWidget)
        self.labelCorespondance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCorespondance.setObjectName("labelCorespondance")
        self.gridLayout.addWidget(self.labelCorespondance, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 12, 1, 1, 1)
        self.lineEditRegistreCommerce = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditRegistreCommerce.setObjectName("lineEditRegistreCommerce")
        self.gridLayout.addWidget(self.lineEditRegistreCommerce, 3, 2, 1, 1)
        self.lineEditFax = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditFax.setObjectName("lineEditFax")
        self.gridLayout.addWidget(self.lineEditFax, 5, 2, 1, 1)
        self.lineEditAdresseBanque = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditAdresseBanque.setObjectName("lineEditAdresseBanque")
        self.gridLayout.addWidget(self.lineEditAdresseBanque, 10, 2, 1, 1)
        self.lineEditNomFournisseur = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditNomFournisseur.setObjectName("lineEditNomFournisseur")
        self.gridLayout.addWidget(self.lineEditNomFournisseur, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 13, 1, 1, 1)
        self.labelFax = QtWidgets.QLabel(FounisseurModificationWidget)
        self.labelFax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFax.setObjectName("labelFax")
        self.gridLayout.addWidget(self.labelFax, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 1, 1, 1)
        self.labelRegistreCommerce = QtWidgets.QLabel(FounisseurModificationWidget)
        self.labelRegistreCommerce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRegistreCommerce.setObjectName("labelRegistreCommerce")
        self.gridLayout.addWidget(self.labelRegistreCommerce, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 14, 1, 1, 1)
        self.labelTelephone = QtWidgets.QLabel(FounisseurModificationWidget)
        self.labelTelephone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTelephone.setObjectName("labelTelephone")
        self.gridLayout.addWidget(self.labelTelephone, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 17, 1, 1, 1)
        self.lineEditAdresse1 = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditAdresse1.setObjectName("lineEditAdresse1")
        self.gridLayout.addWidget(self.lineEditAdresse1, 14, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 1, 1, 1)
        self.lineEditCodeFournisseuri = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditCodeFournisseuri.setObjectName("lineEditCodeFournisseuri")
        self.gridLayout.addWidget(self.lineEditCodeFournisseuri, 0, 2, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.gridLayout.addWidget(self.lineEditEmail, 8, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(FounisseurModificationWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 16, 1, 1, 1)
        self.lineEditRemarque2 = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditRemarque2.setObjectName("lineEditRemarque2")
        self.gridLayout.addWidget(self.lineEditRemarque2, 16, 2, 1, 1)
        self.lineEditRemarque1 = QtWidgets.QLineEdit(FounisseurModificationWidget)
        self.lineEditRemarque1.setObjectName("lineEditRemarque1")
        self.gridLayout.addWidget(self.lineEditRemarque1, 15, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButtonSauvgarder = QtWidgets.QPushButton(FounisseurModificationWidget)
        self.pushButtonSauvgarder.setObjectName("pushButtonSauvgarder")
        self.horizontalLayout_3.addWidget(self.pushButtonSauvgarder)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(FounisseurModificationWidget)
        QtCore.QMetaObject.connectSlotsByName(FounisseurModificationWidget)

    def retranslateUi(self, FounisseurModificationWidget):
        _translate = QtCore.QCoreApplication.translate
        FounisseurModificationWidget.setWindowTitle(_translate("FounisseurModificationWidget", "FounisseurModificationWidget"))
        self.label.setText(_translate("FounisseurModificationWidget", "Rechercher pour modifier"))
        self.pushButtonRechercher.setText(_translate("FounisseurModificationWidget", "Rechercher"))
        self.labelEmail.setText(_translate("FounisseurModificationWidget", "Email"))
        self.label_17.setText(_translate("FounisseurModificationWidget", "Compte B"))
        self.label_12.setText(_translate("FounisseurModificationWidget", "Remarque 1"))
        self.label_2.setText(_translate("FounisseurModificationWidget", "Code Fournisseuri"))
        self.label_4.setText(_translate("FounisseurModificationWidget", "Code Fourisseur"))
        self.labelSiteWeb.setText(_translate("FounisseurModificationWidget", "Site Web"))
        self.labelCorespondance.setText(_translate("FounisseurModificationWidget", "C Corespandance"))
        self.label_3.setText(_translate("FounisseurModificationWidget", "Nom Fournisseur"))
        self.label_18.setText(_translate("FounisseurModificationWidget", "Adresse Fournisseur"))
        self.label_16.setText(_translate("FounisseurModificationWidget", "Adresse"))
        self.labelFax.setText(_translate("FounisseurModificationWidget", "Fax"))
        self.label_15.setText(_translate("FounisseurModificationWidget", "Adresse Banque"))
        self.labelRegistreCommerce.setText(_translate("FounisseurModificationWidget", "Registre de commerce"))
        self.label_14.setText(_translate("FounisseurModificationWidget", "Adresse 1"))
        self.labelTelephone.setText(_translate("FounisseurModificationWidget", "Telephone"))
        self.label_10.setText(_translate("FounisseurModificationWidget", "Flag"))
        self.label_13.setText(_translate("FounisseurModificationWidget", "Fichier"))
        self.label_11.setText(_translate("FounisseurModificationWidget", "Remarque 2"))
        self.pushButtonSauvgarder.setText(_translate("FounisseurModificationWidget", "Sauvgarder les modification"))
