# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\COZMET\Desktop\todoPyQt\FournisseurRechercherWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FournisseurRechercherWidget(object):
    def setupUi(self, FournisseurRechercherWidget):
        FournisseurRechercherWidget.setObjectName("FournisseurRechercherWidget")
        FournisseurRechercherWidget.resize(615, 492)
        self.gridLayout = QtWidgets.QGridLayout(FournisseurRechercherWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(FournisseurRechercherWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditCle = QtWidgets.QLineEdit(FournisseurRechercherWidget)
        self.lineEditCle.setObjectName("lineEditCle")
        self.horizontalLayout.addWidget(self.lineEditCle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonRechercher = QtWidgets.QPushButton(FournisseurRechercherWidget)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.horizontalLayout_2.addWidget(self.pushButtonRechercher)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(FournisseurRechercherWidget)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)

        self.retranslateUi(FournisseurRechercherWidget)
        QtCore.QMetaObject.connectSlotsByName(FournisseurRechercherWidget)

    def retranslateUi(self, FournisseurRechercherWidget):
        _translate = QtCore.QCoreApplication.translate
        FournisseurRechercherWidget.setWindowTitle(_translate("FournisseurRechercherWidget", "Rechercher"))
        self.label.setText(_translate("FournisseurRechercherWidget", "Code Fournisseur"))
        self.pushButtonRechercher.setText(_translate("FournisseurRechercherWidget", "Rechercher"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FournisseurRechercherWidget", "Num Fournisseuri"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FournisseurRechercherWidget", "Nom Fourn"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FournisseurRechercherWidget", "Num Fournisseur"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FournisseurRechercherWidget", "Registre de commerce"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FournisseurRechercherWidget", "Telephone"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FournisseurRechercherWidget", "Fax"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("FournisseurRechercherWidget", "C Corespondance"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("FournisseurRechercherWidget", "Site Web"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("FournisseurRechercherWidget", "Email"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("FournisseurRechercherWidget", "Fichier"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("FournisseurRechercherWidget", "Adresse Banque"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("FournisseurRechercherWidget", "Compte B"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("FournisseurRechercherWidget", "Adresse Fournisseur"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("FournisseurRechercherWidget", "Adresse"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("FournisseurRechercherWidget", "Adresse 1"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("FournisseurRechercherWidget", "Remarque 1"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("FournisseurRechercherWidget", "Remarque 2"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("FournisseurRechercherWidget", "Flag"))
