# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\COZMET\Desktop\todoPyQt\FournisseurAfficherWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FounisseurAfficherWidget(object):
    def setupUi(self, FounisseurAfficherWidget):
        FounisseurAfficherWidget.setObjectName("FounisseurAfficherWidget")
        FounisseurAfficherWidget.resize(667, 551)
        self.tableWidget = QtWidgets.QTableWidget(FounisseurAfficherWidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 50, 597, 413))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)

        self.retranslateUi(FounisseurAfficherWidget)
        QtCore.QMetaObject.connectSlotsByName(FounisseurAfficherWidget)

    def retranslateUi(self, FounisseurAfficherWidget):
        _translate = QtCore.QCoreApplication.translate
        FounisseurAfficherWidget.setWindowTitle(_translate("FounisseurAfficherWidget", "FournisseurAfficherWidget"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FounisseurAfficherWidget", "Num Fournisseuri"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FounisseurAfficherWidget", "Nom Fourn"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FounisseurAfficherWidget", "Num Fournisseur"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FounisseurAfficherWidget", "Registre de commerce"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FounisseurAfficherWidget", "Telephone"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FounisseurAfficherWidget", "Fax"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("FounisseurAfficherWidget", "C Corespondance"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("FounisseurAfficherWidget", "Site Web"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("FounisseurAfficherWidget", "Email"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("FounisseurAfficherWidget", "Fichier"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("FounisseurAfficherWidget", "Adresse Banque"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("FounisseurAfficherWidget", "Compte B"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("FounisseurAfficherWidget", "Adresse Fournisseur"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("FounisseurAfficherWidget", "Adresse"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("FounisseurAfficherWidget", "Adresse 1"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("FounisseurAfficherWidget", "Remarque 1"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("FounisseurAfficherWidget", "Remarque 2"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("FounisseurAfficherWidget", "Flag"))
