# Generated by Django 3.1.5 on 2021-01-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('tele', models.CharField(max_length=250)),
                ('addresse', models.CharField(max_length=250)),
            ],
        ),
    ]
