# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\COZMET\Desktop\Gestion de patient\ajouterWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AjouterWidget(object):
    def setupUi(self, AjouterWidget):
        AjouterWidget.setObjectName("AjouterWidget")
        AjouterWidget.resize(1039, 928)
        self.widget = QtWidgets.QWidget(AjouterWidget)
        self.widget.setGeometry(QtCore.QRect(180, 200, 681, 211))
        self.widget.setObjectName("widget")
        self.labelAttention = QtWidgets.QLabel(self.widget)
        self.labelAttention.setGeometry(QtCore.QRect(240, 100, 351, 41))
        self.labelAttention.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.labelAttention.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAttention.setObjectName("labelAttention")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(11, 11, 224, 159))
        self.widget1.setObjectName("widget1")
        self.formLayout = QtWidgets.QFormLayout(self.widget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditNom = QtWidgets.QLineEdit(self.widget1)
        self.lineEditNom.setObjectName("lineEditNom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditNom)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditPrenom = QtWidgets.QLineEdit(self.widget1)
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditPrenom)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditTelephone = QtWidgets.QLineEdit(self.widget1)
        self.lineEditTelephone.setObjectName("lineEditTelephone")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditTelephone)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxService = QtWidgets.QComboBox(self.widget1)
        self.comboBoxService.setObjectName("comboBoxService")
        self.comboBoxService.addItem("")
        self.comboBoxService.addItem("")
        self.comboBoxService.addItem("")
        self.comboBoxService.addItem("")
        self.comboBoxService.addItem("")
        self.comboBoxService.addItem("")
        self.comboBoxService.addItem("")
        self.comboBoxService.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxService)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget1)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonSauvgarder = QtWidgets.QPushButton(self.widget1)
        self.pushButtonSauvgarder.setObjectName("pushButtonSauvgarder")
        self.horizontalLayout.addWidget(self.pushButtonSauvgarder)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)

        self.retranslateUi(AjouterWidget)
        QtCore.QMetaObject.connectSlotsByName(AjouterWidget)

    def retranslateUi(self, AjouterWidget):
        _translate = QtCore.QCoreApplication.translate
        AjouterWidget.setWindowTitle(_translate("AjouterWidget", "AjouterWidget"))
        self.labelAttention.setText(_translate("AjouterWidget", "Cette date et heure est déja réservé"))
        self.label.setText(_translate("AjouterWidget", "Nom :"))
        self.label_2.setText(_translate("AjouterWidget", "Prénom :"))
        self.label_3.setText(_translate("AjouterWidget", "N° téléphone :"))
        self.label_4.setText(_translate("AjouterWidget", "Type de service :"))
        self.comboBoxService.setItemText(0, _translate("AjouterWidget", "CS"))
        self.comboBoxService.setItemText(1, _translate("AjouterWidget", "CTRL"))
        self.comboBoxService.setItemText(2, _translate("AjouterWidget", "L.A"))
        self.comboBoxService.setItemText(3, _translate("AjouterWidget", "L.S"))
        self.comboBoxService.setItemText(4, _translate("AjouterWidget", "Polygraphie"))
        self.comboBoxService.setItemText(5, _translate("AjouterWidget", "L.P"))
        self.comboBoxService.setItemText(6, _translate("AjouterWidget", "Prick Test"))
        self.comboBoxService.setItemText(7, _translate("AjouterWidget", "Spirometrie"))
        self.label_5.setText(_translate("AjouterWidget", "Date et Heure"))
        self.pushButtonSauvgarder.setText(_translate("AjouterWidget", "Sauvgarder"))
