# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\COZMET\Desktop\Gestion de patient\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1433, 868)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(17, 60, 181, 31))
        self.label.setStyleSheet("background-color: rgb(177, 146, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(17, 100, 181, 31))
        self.label_2.setStyleSheet("background-color: rgb(61, 210, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(17, 140, 181, 31))
        self.label_3.setStyleSheet("background-color: rgb(42, 42, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 560, 221, 191))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(17, 180, 181, 31))
        self.label_5.setStyleSheet("background-color: rgb(242, 199, 68);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(17, 220, 181, 31))
        self.label_6.setStyleSheet("background-color: rgb(191, 151, 117);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(17, 260, 181, 31))
        self.label_7.setStyleSheet("background-color: rgb(242, 226, 196);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(17, 300, 181, 31))
        self.label_8.setStyleSheet("background-color: rgb(191, 180, 176);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(17, 340, 181, 31))
        self.label_9.setStyleSheet("background-color: rgb(242, 185, 172);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.widgetCentral = QtWidgets.QWidget(self.centralwidget)
        self.widgetCentral.setGeometry(QtCore.QRect(229, 9, 1201, 751))
        self.widgetCentral.setStyleSheet("")
        self.widgetCentral.setObjectName("widgetCentral")
        self.widget = QtWidgets.QWidget(self.widgetCentral)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1051, 771))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(1, 50, 751, 691))
        self.tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setRowCount(19)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.pushButtonPrendreRDV = QtWidgets.QPushButton(self.widget)
        self.pushButtonPrendreRDV.setGeometry(QtCore.QRect(850, 80, 91, 23))
        self.pushButtonPrendreRDV.setObjectName("pushButtonPrendreRDV")
        self.labelDateToday = QtWidgets.QLabel(self.widget)
        self.labelDateToday.setGeometry(QtCore.QRect(0, 0, 751, 41))
        self.labelDateToday.setStyleSheet("font: 75 24pt \"Adobe Caslon Pro Bold\";")
        self.labelDateToday.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDateToday.setObjectName("labelDateToday")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1433, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Consultation"))
        self.label_2.setText(_translate("MainWindow", "Contrôle"))
        self.label_3.setText(_translate("MainWindow", "Lecture des Analyses"))
        self.label_5.setText(_translate("MainWindow", "Lecture de Scanner"))
        self.label_6.setText(_translate("MainWindow", "Polygraphie"))
        self.label_7.setText(_translate("MainWindow", "Lecture de Polygraphie"))
        self.label_8.setText(_translate("MainWindow", "Prick Test"))
        self.label_9.setText(_translate("MainWindow", "Spirometrie"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "08h00"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "08h30"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "09h00"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "09h30"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "10h00"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "10h30"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "11h00"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "11h30"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "12h00"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "12h30"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "13h00"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "13h30"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "14h00"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14h30"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15h00"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "15h30"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "16h00"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "16h30"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "17h00"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "01"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "02"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "03"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "04"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "05"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "06"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "07"))
        self.pushButtonPrendreRDV.setText(_translate("MainWindow", "Prendre un RDV"))
        self.labelDateToday.setText(_translate("MainWindow", "Janvier 2020"))
