# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.Centralwidget = QtWidgets.QWidget(MainWindow)
        self.Centralwidget.setObjectName("Centralwidget")
        MainWindow.setCentralWidget(self.Centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_E_Achats = QtWidgets.QMenu(self.menubar)
        self.menu_E_Achats.setObjectName("menu_E_Achats")
        self.menu_Referencement = QtWidgets.QMenu(self.menubar)
        self.menu_Referencement.setObjectName("menu_Referencement")
        self.menu_E_Achats1 = QtWidgets.QMenu(self.menubar)
        self.menu_E_Achats1.setObjectName("menu_E_Achats1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEnt_cmd = QtWidgets.QAction(MainWindow)
        self.actionEnt_cmd.setObjectName("actionEnt_cmd")
        self.actionDet_cmd = QtWidgets.QAction(MainWindow)
        self.actionDet_cmd.setObjectName("actionDet_cmd")
        self.actionT_frns = QtWidgets.QAction(MainWindow)
        self.actionT_frns.setObjectName("actionT_frns")
        self.actionT_produits = QtWidgets.QAction(MainWindow)
        self.actionT_produits.setObjectName("actionT_produits")
        self.actionCmd_hist = QtWidgets.QAction(MainWindow)
        self.actionCmd_hist.setObjectName("actionCmd_hist")
        self.menu_E_Achats.addAction(self.actionEnt_cmd)
        self.menu_E_Achats.addAction(self.actionDet_cmd)
        self.menu_Referencement.addAction(self.actionT_frns)
        self.menu_Referencement.addAction(self.actionT_produits)
        self.menu_E_Achats1.addAction(self.actionCmd_hist)
        self.menubar.addAction(self.menu_E_Achats.menuAction())
        self.menubar.addAction(self.menu_Referencement.menuAction())
        self.menubar.addAction(self.menu_E_Achats.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_E_Achats.setTitle(_translate("MainWindow", "E_Achats"))
        self.menu_Referencement.setTitle(_translate("MainWindow", "Referencement"))
        self.menu_E_Achats1.setTitle(_translate("MainWindow", "E_Achats"))
        self.actionEnt_cmd.setText(_translate("MainWindow", "Ent_cmd"))
        self.actionDet_cmd.setText(_translate("MainWindow", "Det_cmd"))
        self.actionT_frns.setText(_translate("MainWindow", "T_frns"))
        self.actionT_produits.setText(_translate("MainWindow", "T_produits"))
        self.actionCmd_hist.setText(_translate("MainWindow", "Cmd_hist"))
