# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T_frnsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_T_frns(object):
    def setupUi(self, T_frns):
        T_frns.setObjectName("T_frns")
        T_frns.resize(686, 602)
        self.widgetCentralT_frns = QtWidgets.QWidget(T_frns)
        self.widgetCentralT_frns.setGeometry(QtCore.QRect(120, 20, 491, 391))
        self.widgetCentralT_frns.setObjectName("widgetCentralT_frns")
        self.label_T_frns = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.label_T_frns.setGeometry(QtCore.QRect(10, 0, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_T_frns.setFont(font)
        self.label_T_frns.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T_frns.setObjectName("label_T_frns")
        self.lbl_code_frnsi = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_code_frnsi.setGeometry(QtCore.QRect(100, 30, 71, 16))
        self.lbl_code_frnsi.setObjectName("lbl_code_frnsi")
        self.txt_code_frnsi = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_code_frnsi.setGeometry(QtCore.QRect(180, 30, 500, 21))
        self.txt_code_frnsi.setObjectName("txt_code_frnsi")
        self.lbl_Date_deb = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_Date_deb.setGeometry(QtCore.QRect(100, 60, 71, 16))
        self.lbl_Date_deb.setObjectName("lbl_Date_deb")
        self.txt_Date_deb = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_Date_deb.setGeometry(QtCore.QRect(180, 60, 500, 21))
        self.txt_Date_deb.setObjectName("txt_Date_deb")
        self.lbl_capital = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_capital.setGeometry(QtCore.QRect(100, 90, 71, 16))
        self.lbl_capital.setObjectName("lbl_capital")
        self.txt_capital = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_capital.setGeometry(QtCore.QRect(180, 90, 500, 21))
        self.txt_capital.setObjectName("txt_capital")
        self.lbl_rmq_type_etat = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_rmq_type_etat.setGeometry(QtCore.QRect(100, 120, 71, 16))
        self.lbl_rmq_type_etat.setObjectName("lbl_rmq_type_etat")
        self.txt_rmq_type_etat = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_rmq_type_etat.setGeometry(QtCore.QRect(180, 120, 500, 21))
        self.txt_rmq_type_etat.setObjectName("txt_rmq_type_etat")
        self.lbl_nom_frns = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_nom_frns.setGeometry(QtCore.QRect(100, 150, 71, 16))
        self.lbl_nom_frns.setObjectName("lbl_nom_frns")
        self.txt_nom_frns = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_nom_frns.setGeometry(QtCore.QRect(180, 150, 500, 21))
        self.txt_nom_frns.setObjectName("txt_nom_frns")
        self.lbl_regc = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_regc.setGeometry(QtCore.QRect(100, 180, 71, 16))
        self.lbl_regc.setObjectName("lbl_regc")
        self.txt_regc = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_regc.setGeometry(QtCore.QRect(180, 180, 500, 21))
        self.txt_regc.setObjectName("txt_regc")
        self.lbl_tel = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_tel.setGeometry(QtCore.QRect(100, 210, 71, 16))
        self.lbl_tel.setObjectName("lbl_tel")
        self.txt_tel = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_tel.setGeometry(QtCore.QRect(180, 210, 500, 21))
        self.txt_tel.setObjectName("txt_tel")
        self.lbl_fax = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_fax.setGeometry(QtCore.QRect(100, 240, 71, 16))
        self.lbl_fax.setObjectName("lbl_fax")
        self.txt_fax = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_fax.setGeometry(QtCore.QRect(180, 240, 500, 21))
        self.txt_fax.setObjectName("txt_fax")
        self.lbl_adrs1 = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_adrs1.setGeometry(QtCore.QRect(100, 270, 71, 16))
        self.lbl_adrs1.setObjectName("lbl_adrs1")
        self.txt_adrs1 = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_adrs1.setGeometry(QtCore.QRect(180, 270, 500, 21))
        self.txt_adrs1.setObjectName("txt_adrs1")
        self.lbl_rmq1 = QtWidgets.QLabel(self.widgetCentralT_frns)
        self.lbl_rmq1.setGeometry(QtCore.QRect(100, 300, 71, 16))
        self.lbl_rmq1.setObjectName("lbl_rmq1")
        self.txt_rmq1 = QtWidgets.QLineEdit(self.widgetCentralT_frns)
        self.txt_rmq1.setGeometry(QtCore.QRect(180, 300, 500, 21))
        self.txt_rmq1.setObjectName("txt_rmq1")
        self.pushButton_new = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_new.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.pushButton_new.setObjectName("pushButton_new")
        self.pushButton_add = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_add.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_find = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_find.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.pushButton_find.setObjectName("pushButton_find")
        self.pushButton_upd = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_upd.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.pushButton_upd.setObjectName("pushButton_upd")
        self.pushButton_rmv = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_rmv.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.pushButton_rmv.setObjectName("pushButton_rmv")
        self.pushButton_lst = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_lst.setGeometry(QtCore.QRect(10, 180, 75, 23))
        self.pushButton_lst.setObjectName("pushButton_lst")
        self.pushButton_fst = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_fst.setGeometry(QtCore.QRect(10, 210, 75, 23))
        self.pushButton_fst.setObjectName("pushButton_fst")
        self.pushButton_prev = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_prev.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.pushButton_prev.setObjectName("pushButton_prev")
        self.pushButton_next = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_next.setGeometry(QtCore.QRect(10, 270, 75, 23))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_grid = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_grid.setGeometry(QtCore.QRect(10, 300, 75, 23))
        self.pushButton_grid.setObjectName("pushButton_grid")
        self.pushButton_report = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_report.setGeometry(QtCore.QRect(10, 330, 75, 23))
        self.pushButton_report.setObjectName("pushButton_report")
        self.pushButton_exit = QtWidgets.QPushButton(self.widgetCentralT_frns)
        self.pushButton_exit.setGeometry(QtCore.QRect(10, 360, 75, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.retranslateUi(T_frns)
        QtCore.QMetaObject.connectSlotsByName(T_frns)

    def retranslateUi(self, T_frns):
        _translate = QtCore.QCoreApplication.translate
        T_frns.setWindowTitle(_translate("T_frns", "Form"))
        self.label_T_frns.setText(_translate("T_frns", "T_frns"))
        self.lbl_code_frnsi.setText(_translate("T_frns", "code_frnsi"))
        self.lbl_Date_deb.setText(_translate("T_frns", "Date_deb"))
        self.lbl_capital.setText(_translate("T_frns", "capital"))
        self.lbl_rmq_type_etat.setText(_translate("T_frns", "rmq_type_etat"))
        self.lbl_nom_frns.setText(_translate("T_frns", "nom_frns"))
        self.lbl_regc.setText(_translate("T_frns", "regc"))
        self.lbl_tel.setText(_translate("T_frns", "tel"))
        self.lbl_fax.setText(_translate("T_frns", "fax"))
        self.lbl_adrs1.setText(_translate("T_frns", "adrs1"))
        self.lbl_rmq1.setText(_translate("T_frns", "rmq1"))
        self.pushButton_new.setText(_translate("T_frns", "Nouveau"))
        self.pushButton_add.setText(_translate("T_frns", "Ajouter"))
        self.pushButton_find.setText(_translate("T_frns", "Rechercher"))
        self.pushButton_upd.setText(_translate("T_frns", "Modifier"))
        self.pushButton_rmv.setText(_translate("T_frns", "Supprimer"))
        self.pushButton_lst.setText(_translate("T_frns", "Dernier"))
        self.pushButton_fst.setText(_translate("T_frns", "Premier"))
        self.pushButton_prev.setText(_translate("T_frns", "Precedent"))
        self.pushButton_next.setText(_translate("T_frns", "Suivant"))
        self.pushButton_grid.setText(_translate("T_frns", "Tableau"))
        self.pushButton_report.setText(_translate("T_frns", "Etat"))
        self.pushButton_exit.setText(_translate("T_frns", "Quitter"))
