# Generated by Django 3.1.5 on 2021-01-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familleProduit', '0002_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='familleProduit',
        ),
    ]
