# Generated by Django 3.1.5 on 2021-01-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familleProduit', '0003_remove_produit_familleproduit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
