# Generated by Django 3.1.5 on 2021-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familleProduit', '0005_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='familleproduit',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
