# Generated by Django 3.1.5 on 2021-01-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familleProduit', '0006_familleproduit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familleproduit',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
