# Generated by Django 3.1.5 on 2021-01-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familleProduit', '0007_auto_20210124_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familleproduit',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
