# Generated by Django 3.1.5 on 2021-01-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familleProduit', '0008_auto_20210124_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familleproduit',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
