# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commandeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommandeWidget(object):
    def setupUi(self, CommandeWidget):
        CommandeWidget.setObjectName("CommandeWidget")
        CommandeWidget.resize(697, 663)
        self.widgetCentral = QtWidgets.QWidget(CommandeWidget)
        self.widgetCentral.setGeometry(QtCore.QRect(9, 9, 671, 641))
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonNouveau = QtWidgets.QPushButton(self.widgetCentral)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.verticalLayout.addWidget(self.pushButtonNouveau)
        self.pushButtonValider = QtWidgets.QPushButton(self.widgetCentral)
        self.pushButtonValider.setObjectName("pushButtonValider")
        self.verticalLayout.addWidget(self.pushButtonValider)
        self.pushButtonImprimer = QtWidgets.QPushButton(self.widgetCentral)
        self.pushButtonImprimer.setObjectName("pushButtonImprimer")
        self.verticalLayout.addWidget(self.pushButtonImprimer)
        self.pushButtonSortir = QtWidgets.QPushButton(self.widgetCentral)
        self.pushButtonSortir.setObjectName("pushButtonSortir")
        self.verticalLayout.addWidget(self.pushButtonSortir)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.widgetCentral)
        self.tabWidget.setMinimumSize(QtCore.QSize(131, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditCodeCmd = QtWidgets.QLineEdit(self.tab)
        self.lineEditCodeCmd.setEnabled(False)
        self.lineEditCodeCmd.setObjectName("lineEditCodeCmd")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditCodeCmd)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditRefMarche = QtWidgets.QLineEdit(self.tab)
        self.lineEditRefMarche.setObjectName("lineEditRefMarche")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditRefMarche)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBoxCodeFournisseur = QtWidgets.QComboBox(self.tab)
        self.comboBoxCodeFournisseur.setMinimumSize(QtCore.QSize(131, 0))
        self.comboBoxCodeFournisseur.setObjectName("comboBoxCodeFournisseur")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxCodeFournisseur)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditCodeSociete = QtWidgets.QLineEdit(self.tab)
        self.lineEditCodeSociete.setObjectName("lineEditCodeSociete")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditCodeSociete)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.dateEditDateCommande = QtWidgets.QDateEdit(self.tab)
        self.dateEditDateCommande.setMinimumSize(QtCore.QSize(131, 0))
        self.dateEditDateCommande.setObjectName("dateEditDateCommande")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateEditDateCommande)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEditFlag = QtWidgets.QLineEdit(self.tab)
        self.lineEditFlag.setObjectName("lineEditFlag")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditFlag)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEditRemarqueEntet = QtWidgets.QLineEdit(self.tab)
        self.lineEditRemarqueEntet.setObjectName("lineEditRemarqueEntet")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEditRemarqueEntet)
        self.gridLayout.addLayout(self.formLayout_2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEditIdCommande = QtWidgets.QLineEdit(self.widget)
        self.lineEditIdCommande.setEnabled(False)
        self.lineEditIdCommande.setObjectName("lineEditIdCommande")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditIdCommande)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEditFKCommande = QtWidgets.QLineEdit(self.widget)
        self.lineEditFKCommande.setEnabled(False)
        self.lineEditFKCommande.setObjectName("lineEditFKCommande")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditFKCommande)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBoxRefProduit = QtWidgets.QComboBox(self.widget)
        self.comboBoxRefProduit.setMinimumSize(QtCore.QSize(131, 0))
        self.comboBoxRefProduit.setCurrentText("")
        self.comboBoxRefProduit.setObjectName("comboBoxRefProduit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxRefProduit)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEditQuantite = QtWidgets.QLineEdit(self.widget)
        self.lineEditQuantite.setObjectName("lineEditQuantite")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditQuantite)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEditPrixUnite = QtWidgets.QLineEdit(self.widget)
        self.lineEditPrixUnite.setObjectName("lineEditPrixUnite")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditPrixUnite)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.dateEditDateLivraison = QtWidgets.QDateEdit(self.widget)
        self.dateEditDateLivraison.setCalendarPopup(True)
        self.dateEditDateLivraison.setObjectName("dateEditDateLivraison")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateEditDateLivraison)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.comboBoxCodeUnite = QtWidgets.QComboBox(self.widget)
        self.comboBoxCodeUnite.setMinimumSize(QtCore.QSize(131, 0))
        self.comboBoxCodeUnite.setObjectName("comboBoxCodeUnite")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBoxCodeUnite)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEditPrixGlobal = QtWidgets.QLineEdit(self.widget)
        self.lineEditPrixGlobal.setEnabled(False)
        self.lineEditPrixGlobal.setObjectName("lineEditPrixGlobal")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEditPrixGlobal)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEditRemarqueDetail = QtWidgets.QLineEdit(self.widget)
        self.lineEditRemarqueDetail.setObjectName("lineEditRemarqueDetail")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEditRemarqueDetail)
        self.horizontalLayout_2.addWidget(self.widget)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.pushButtonAjouter = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonAjouter.setEnabled(False)
        self.pushButtonAjouter.setObjectName("pushButtonAjouter")
        self.verticalLayout_2.addWidget(self.pushButtonAjouter)
        self.pushButtonModifier = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonModifier.setEnabled(False)
        self.pushButtonModifier.setObjectName("pushButtonModifier")
        self.verticalLayout_2.addWidget(self.pushButtonModifier)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonSupprimer.setEnabled(False)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.verticalLayout_2.addWidget(self.pushButtonSupprimer)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tableWidgetEntete = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetEntete.setObjectName("tableWidgetEntete")
        self.tableWidgetEntete.setColumnCount(9)
        self.tableWidgetEntete.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEntete.setHorizontalHeaderItem(8, item)
        self.verticalLayout_3.addWidget(self.tableWidgetEntete)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBoxChoixRecherche = QtWidgets.QComboBox(self.tab_3)
        self.comboBoxChoixRecherche.setGeometry(QtCore.QRect(130, 20, 111, 22))
        self.comboBoxChoixRecherche.setObjectName("comboBoxChoixRecherche")
        self.comboBoxChoixRecherche.addItem("")
        self.comboBoxChoixRecherche.addItem("")
        self.pushButtonRechercher = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonRechercher.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.tableWidgetRechercher = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidgetRechercher.setGeometry(QtCore.QRect(10, 110, 541, 381))
        self.tableWidgetRechercher.setObjectName("tableWidgetRechercher")
        self.tableWidgetRechercher.setColumnCount(0)
        self.tableWidgetRechercher.setRowCount(0)
        self.pushButtonModifierRechercher = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonModifierRechercher.setEnabled(False)
        self.pushButtonModifierRechercher.setGeometry(QtCore.QRect(80, 530, 75, 23))
        self.pushButtonModifierRechercher.setObjectName("pushButtonModifierRechercher")
        self.pushButtonSupprimerRechercher = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonSupprimerRechercher.setEnabled(False)
        self.pushButtonSupprimerRechercher.setGeometry(QtCore.QRect(370, 530, 75, 23))
        self.pushButtonSupprimerRechercher.setObjectName("pushButtonSupprimerRechercher")
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(CommandeWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CommandeWidget)

    def retranslateUi(self, CommandeWidget):
        _translate = QtCore.QCoreApplication.translate
        CommandeWidget.setWindowTitle(_translate("CommandeWidget", "Form"))
        self.pushButtonNouveau.setText(_translate("CommandeWidget", "Nouveau"))
        self.pushButtonValider.setText(_translate("CommandeWidget", "Valider"))
        self.pushButtonImprimer.setText(_translate("CommandeWidget", "Imprimer"))
        self.pushButtonSortir.setText(_translate("CommandeWidget", "Soritir"))
        self.label.setText(_translate("CommandeWidget", "Code _cmd"))
        self.label_4.setText(_translate("CommandeWidget", "Ref Marche"))
        self.label_2.setText(_translate("CommandeWidget", "Code Fournisseur"))
        self.label_3.setText(_translate("CommandeWidget", "Code Societe"))
        self.label_5.setText(_translate("CommandeWidget", "Date Commande"))
        self.label_7.setText(_translate("CommandeWidget", "Flag"))
        self.label_6.setText(_translate("CommandeWidget", "Remarque"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CommandeWidget", "Entete"))
        self.label_8.setText(_translate("CommandeWidget", "Id Commande"))
        self.label_9.setText(_translate("CommandeWidget", "FK Commande"))
        self.label_10.setText(_translate("CommandeWidget", "Ref Produit"))
        self.label_11.setText(_translate("CommandeWidget", "Quantité demandé"))
        self.label_12.setText(_translate("CommandeWidget", "Prix de Unité"))
        self.label_13.setText(_translate("CommandeWidget", "Date de Livraison Souhaitée"))
        self.label_14.setText(_translate("CommandeWidget", "Code Unité"))
        self.label_15.setText(_translate("CommandeWidget", "Prix Global"))
        self.label_16.setText(_translate("CommandeWidget", "Remarque"))
        self.pushButtonAjouter.setText(_translate("CommandeWidget", "Ajouter"))
        self.pushButtonModifier.setText(_translate("CommandeWidget", "Modifier"))
        self.pushButtonSupprimer.setText(_translate("CommandeWidget", "Supprimer"))
        item = self.tableWidgetEntete.horizontalHeaderItem(0)
        item.setText(_translate("CommandeWidget", "id commande"))
        item = self.tableWidgetEntete.horizontalHeaderItem(1)
        item.setText(_translate("CommandeWidget", "fk commande"))
        item = self.tableWidgetEntete.horizontalHeaderItem(2)
        item.setText(_translate("CommandeWidget", "ref produit"))
        item = self.tableWidgetEntete.horizontalHeaderItem(3)
        item.setText(_translate("CommandeWidget", "quantite"))
        item = self.tableWidgetEntete.horizontalHeaderItem(4)
        item.setText(_translate("CommandeWidget", "prix unite"))
        item = self.tableWidgetEntete.horizontalHeaderItem(5)
        item.setText(_translate("CommandeWidget", "date livraison"))
        item = self.tableWidgetEntete.horizontalHeaderItem(6)
        item.setText(_translate("CommandeWidget", "code unité"))
        item = self.tableWidgetEntete.horizontalHeaderItem(7)
        item.setText(_translate("CommandeWidget", "Prix global"))
        item = self.tableWidgetEntete.horizontalHeaderItem(8)
        item.setText(_translate("CommandeWidget", "remarque"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CommandeWidget", "Detail"))
        self.comboBoxChoixRecherche.setItemText(0, _translate("CommandeWidget", "Entete"))
        self.comboBoxChoixRecherche.setItemText(1, _translate("CommandeWidget", "Detail"))
        self.pushButtonRechercher.setText(_translate("CommandeWidget", "Rechercher"))
        self.pushButtonModifierRechercher.setText(_translate("CommandeWidget", "Selectionner"))
        self.pushButtonSupprimerRechercher.setText(_translate("CommandeWidget", "Supprimer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("CommandeWidget", "Recherche"))
