# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FournisseurValideWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FounisseurValideWidget(object):
    def setupUi(self, FounisseurValideWidget):
        FounisseurValideWidget.setObjectName("FounisseurValideWidget")
        FounisseurValideWidget.resize(640, 702)
        self.labelImage = QtWidgets.QLabel(FounisseurValideWidget)
        self.labelImage.setGeometry(QtCore.QRect(280, 420, 151, 101))
        self.labelImage.setMinimumSize(QtCore.QSize(0, 0))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.labelCatalogue = QtWidgets.QLabel(FounisseurValideWidget)
        self.labelCatalogue.setGeometry(QtCore.QRect(110, 550, 141, 81))
        self.labelCatalogue.setText("")
        self.labelCatalogue.setObjectName("labelCatalogue")
        self.widget = QtWidgets.QWidget(FounisseurValideWidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 247, 522))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditCodeFournisseuri = QtWidgets.QLineEdit(self.widget)
        self.lineEditCodeFournisseuri.setEnabled(False)
        self.lineEditCodeFournisseuri.setObjectName("lineEditCodeFournisseuri")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditCodeFournisseuri)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditNomFournisseur = QtWidgets.QLineEdit(self.widget)
        self.lineEditNomFournisseur.setObjectName("lineEditNomFournisseur")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditNomFournisseur)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditCodeFounisseur = QtWidgets.QLineEdit(self.widget)
        self.lineEditCodeFounisseur.setObjectName("lineEditCodeFounisseur")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditCodeFounisseur)
        self.labelRegistreCommerce = QtWidgets.QLabel(self.widget)
        self.labelRegistreCommerce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRegistreCommerce.setObjectName("labelRegistreCommerce")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelRegistreCommerce)
        self.lineEditRegistreCommerce = QtWidgets.QLineEdit(self.widget)
        self.lineEditRegistreCommerce.setObjectName("lineEditRegistreCommerce")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditRegistreCommerce)
        self.labelTelephone = QtWidgets.QLabel(self.widget)
        self.labelTelephone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTelephone.setObjectName("labelTelephone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelTelephone)
        self.lineEditTelephone = QtWidgets.QLineEdit(self.widget)
        self.lineEditTelephone.setObjectName("lineEditTelephone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditTelephone)
        self.labelFax = QtWidgets.QLabel(self.widget)
        self.labelFax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFax.setObjectName("labelFax")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelFax)
        self.lineEditFax = QtWidgets.QLineEdit(self.widget)
        self.lineEditFax.setObjectName("lineEditFax")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditFax)
        self.labelCorespondance = QtWidgets.QLabel(self.widget)
        self.labelCorespondance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCorespondance.setObjectName("labelCorespondance")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelCorespondance)
        self.lineEditCorespondance = QtWidgets.QLineEdit(self.widget)
        self.lineEditCorespondance.setObjectName("lineEditCorespondance")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEditCorespondance)
        self.labelSiteWeb = QtWidgets.QLabel(self.widget)
        self.labelSiteWeb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSiteWeb.setObjectName("labelSiteWeb")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelSiteWeb)
        self.lineEditSiteWeb = QtWidgets.QLineEdit(self.widget)
        self.lineEditSiteWeb.setObjectName("lineEditSiteWeb")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEditSiteWeb)
        self.labelEmail = QtWidgets.QLabel(self.widget)
        self.labelEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEmail.setObjectName("labelEmail")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(self.widget)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEditEmail)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEditFichier = QtWidgets.QLineEdit(self.widget)
        self.lineEditFichier.setObjectName("lineEditFichier")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEditFichier)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEditAdresseBanque = QtWidgets.QLineEdit(self.widget)
        self.lineEditAdresseBanque.setObjectName("lineEditAdresseBanque")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEditAdresseBanque)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEditCompteB = QtWidgets.QLineEdit(self.widget)
        self.lineEditCompteB.setObjectName("lineEditCompteB")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEditCompteB)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEditAdresseFournisseur = QtWidgets.QLineEdit(self.widget)
        self.lineEditAdresseFournisseur.setObjectName("lineEditAdresseFournisseur")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEditAdresseFournisseur)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEditAdresse = QtWidgets.QLineEdit(self.widget)
        self.lineEditAdresse.setObjectName("lineEditAdresse")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEditAdresse)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEditAdresse1 = QtWidgets.QLineEdit(self.widget)
        self.lineEditAdresse1.setObjectName("lineEditAdresse1")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEditAdresse1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEditRemarque1 = QtWidgets.QLineEdit(self.widget)
        self.lineEditRemarque1.setObjectName("lineEditRemarque1")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEditRemarque1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEditRemarque2 = QtWidgets.QLineEdit(self.widget)
        self.lineEditRemarque2.setObjectName("lineEditRemarque2")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.lineEditRemarque2)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEditFlag = QtWidgets.QLineEdit(self.widget)
        self.lineEditFlag.setObjectName("lineEditFlag")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.lineEditFlag)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pushButtonAjouterImage = QtWidgets.QPushButton(self.widget)
        self.pushButtonAjouterImage.setObjectName("pushButtonAjouterImage")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.pushButtonAjouterImage)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pushButtonAjouterCatalogue = QtWidgets.QPushButton(self.widget)
        self.pushButtonAjouterCatalogue.setObjectName("pushButtonAjouterCatalogue")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.pushButtonAjouterCatalogue)

        self.retranslateUi(FounisseurValideWidget)
        QtCore.QMetaObject.connectSlotsByName(FounisseurValideWidget)

    def retranslateUi(self, FounisseurValideWidget):
        _translate = QtCore.QCoreApplication.translate
        FounisseurValideWidget.setWindowTitle(_translate("FounisseurValideWidget", "Fournisseur"))
        self.label.setText(_translate("FounisseurValideWidget", "Code Fournisseuri"))
        self.label_2.setText(_translate("FounisseurValideWidget", "Nom Fournisseur"))
        self.label_3.setText(_translate("FounisseurValideWidget", "Code Fourisseur"))
        self.labelRegistreCommerce.setText(_translate("FounisseurValideWidget", "Registre de commerce"))
        self.labelTelephone.setText(_translate("FounisseurValideWidget", "Telephone"))
        self.labelFax.setText(_translate("FounisseurValideWidget", "Fax"))
        self.labelCorespondance.setText(_translate("FounisseurValideWidget", "C Corespandance"))
        self.labelSiteWeb.setText(_translate("FounisseurValideWidget", "Site Web"))
        self.labelEmail.setText(_translate("FounisseurValideWidget", "Email"))
        self.label_13.setText(_translate("FounisseurValideWidget", "Fichier"))
        self.label_15.setText(_translate("FounisseurValideWidget", "Adresse Banque"))
        self.label_17.setText(_translate("FounisseurValideWidget", "Compte B"))
        self.label_18.setText(_translate("FounisseurValideWidget", "Adresse Fournisseur"))
        self.label_16.setText(_translate("FounisseurValideWidget", "Adresse"))
        self.label_14.setText(_translate("FounisseurValideWidget", "Adresse 1"))
        self.label_12.setText(_translate("FounisseurValideWidget", "Remarque 1"))
        self.label_11.setText(_translate("FounisseurValideWidget", "Remarque 2"))
        self.label_10.setText(_translate("FounisseurValideWidget", "Flag"))
        self.label_4.setText(_translate("FounisseurValideWidget", "Image "))
        self.pushButtonAjouterImage.setText(_translate("FounisseurValideWidget", "Importer "))
        self.label_5.setText(_translate("FounisseurValideWidget", "Catalogue"))
        self.pushButtonAjouterCatalogue.setText(_translate("FounisseurValideWidget", "Importer"))
