# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Entete_Detial.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnteteDetail(object):
    def setupUi(self, EnteteDetail):
        EnteteDetail.setObjectName("EnteteDetail")
        EnteteDetail.resize(837, 720)
        self.widgetCentral = QtWidgets.QWidget(EnteteDetail)
        self.widgetCentral.setGeometry(QtCore.QRect(9, 9, 771, 698))
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.widgetContainerButton = QtWidgets.QWidget(self.widgetCentral)
        self.widgetContainerButton.setMinimumSize(QtCore.QSize(93, 621))
        self.widgetContainerButton.setObjectName("widgetContainerButton")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetContainerButton)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonNouveau = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.verticalLayout.addWidget(self.pushButtonNouveau)
        self.pushButtonValider = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonValider.setObjectName("pushButtonValider")
        self.verticalLayout.addWidget(self.pushButtonValider)
        self.pushButtonRechercher = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonRechercher.setEnabled(False)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.verticalLayout.addWidget(self.pushButtonRechercher)
        self.pushButtonModifier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonModifier.setEnabled(False)
        self.pushButtonModifier.setObjectName("pushButtonModifier")
        self.verticalLayout.addWidget(self.pushButtonModifier)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonSupprimer.setEnabled(False)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.verticalLayout.addWidget(self.pushButtonSupprimer)
        self.pushButtonPremier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonPremier.setObjectName("pushButtonPremier")
        self.verticalLayout.addWidget(self.pushButtonPremier)
        self.pushButtonDernier = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonDernier.setObjectName("pushButtonDernier")
        self.verticalLayout.addWidget(self.pushButtonDernier)
        self.pushButtonAvant = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonAvant.setEnabled(False)
        self.pushButtonAvant.setObjectName("pushButtonAvant")
        self.verticalLayout.addWidget(self.pushButtonAvant)
        self.pushButtonArriere = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonArriere.setEnabled(False)
        self.pushButtonArriere.setObjectName("pushButtonArriere")
        self.verticalLayout.addWidget(self.pushButtonArriere)
        self.pushButtonImprimer = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimer.setEnabled(True)
        self.pushButtonImprimer.setObjectName("pushButtonImprimer")
        self.verticalLayout.addWidget(self.pushButtonImprimer)
        self.pushButtonImprimerTout = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonImprimerTout.setEnabled(True)
        self.pushButtonImprimerTout.setObjectName("pushButtonImprimerTout")
        self.verticalLayout.addWidget(self.pushButtonImprimerTout)
        self.pushButtonVisualiser = QtWidgets.QPushButton(self.widgetContainerButton)
        self.pushButtonVisualiser.setObjectName("pushButtonVisualiser")
        self.verticalLayout.addWidget(self.pushButtonVisualiser)
        spacerItem = QtWidgets.QSpacerItem(20, 314, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_52.addWidget(self.widgetContainerButton)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_Entete = QtWidgets.QGroupBox(self.widgetCentral)
        self.groupBox_Entete.setMaximumSize(QtCore.QSize(681, 171))
        self.groupBox_Entete.setObjectName("groupBox_Entete")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Entete)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_code_cmd = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_code_cmd.setObjectName("label_code_cmd")
        self.horizontalLayout.addWidget(self.label_code_cmd)
        self.lineEdit_int_code_cmd = QtWidgets.QLineEdit(self.groupBox_Entete)
        self.lineEdit_int_code_cmd.setEnabled(False)
        self.lineEdit_int_code_cmd.setObjectName("lineEdit_int_code_cmd")
        self.horizontalLayout.addWidget(self.lineEdit_int_code_cmd)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_flag = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_flag.setObjectName("label_flag")
        self.horizontalLayout_12.addWidget(self.label_flag)
        self.lineEdit_text_flag = QtWidgets.QLineEdit(self.groupBox_Entete)
        self.lineEdit_text_flag.setObjectName("lineEdit_text_flag")
        self.horizontalLayout_12.addWidget(self.lineEdit_text_flag)
        self.gridLayout.addLayout(self.horizontalLayout_12, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_refmarche = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_refmarche.setObjectName("label_refmarche")
        self.horizontalLayout_2.addWidget(self.label_refmarche)
        self.lineEdit_text_refmarche = QtWidgets.QLineEdit(self.groupBox_Entete)
        self.lineEdit_text_refmarche.setObjectName("lineEdit_text_refmarche")
        self.horizontalLayout_2.addWidget(self.lineEdit_text_refmarche)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_remarques = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_remarques.setObjectName("label_remarques")
        self.horizontalLayout_13.addWidget(self.label_remarques)
        self.lineEdit_text_remarques = QtWidgets.QLineEdit(self.groupBox_Entete)
        self.lineEdit_text_remarques.setObjectName("lineEdit_text_remarques")
        self.horizontalLayout_13.addWidget(self.lineEdit_text_remarques)
        self.gridLayout.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_code_frnsi = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_code_frnsi.setObjectName("label_code_frnsi")
        self.horizontalLayout_9.addWidget(self.label_code_frnsi)
        self.comboBox_code_frnsi = QtWidgets.QComboBox(self.groupBox_Entete)
        self.comboBox_code_frnsi.setObjectName("comboBox_code_frnsi")
        self.horizontalLayout_9.addWidget(self.comboBox_code_frnsi)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_util_ENT_cmd = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_util_ENT_cmd.setObjectName("label_util_ENT_cmd")
        self.horizontalLayout_14.addWidget(self.label_util_ENT_cmd)
        self.lineEdit_text_util_ENT_cmd = QtWidgets.QLineEdit(self.groupBox_Entete)
        self.lineEdit_text_util_ENT_cmd.setObjectName("lineEdit_text_util_ENT_cmd")
        self.horizontalLayout_14.addWidget(self.lineEdit_text_util_ENT_cmd)
        self.gridLayout.addLayout(self.horizontalLayout_14, 2, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_code_societe = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_code_societe.setObjectName("label_code_societe")
        self.horizontalLayout_10.addWidget(self.label_code_societe)
        self.comboBox_code_societe = QtWidgets.QComboBox(self.groupBox_Entete)
        self.comboBox_code_societe.setObjectName("comboBox_code_societe")
        self.horizontalLayout_10.addWidget(self.comboBox_code_societe)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_flag_ENT_cmd = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_flag_ENT_cmd.setObjectName("label_flag_ENT_cmd")
        self.horizontalLayout_15.addWidget(self.label_flag_ENT_cmd)
        self.lineEdit_text_flag_ENT_cmd = QtWidgets.QLineEdit(self.groupBox_Entete)
        self.lineEdit_text_flag_ENT_cmd.setObjectName("lineEdit_text_flag_ENT_cmd")
        self.horizontalLayout_15.addWidget(self.lineEdit_text_flag_ENT_cmd)
        self.gridLayout.addLayout(self.horizontalLayout_15, 3, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.dateEdit_date_cmd = QtWidgets.QDateEdit(self.groupBox_Entete)
        self.dateEdit_date_cmd.setCalendarPopup(True)
        self.dateEdit_date_cmd.setObjectName("dateEdit_date_cmd")
        self.horizontalLayout_11.addWidget(self.dateEdit_date_cmd)
        self.gridLayout.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_remarque_ENT_cmd = QtWidgets.QLabel(self.groupBox_Entete)
        self.label_remarque_ENT_cmd.setObjectName("label_remarque_ENT_cmd")
        self.horizontalLayout_16.addWidget(self.label_remarque_ENT_cmd)
        self.lineEdit_text_remarque_ENT_cmd = QtWidgets.QLineEdit(self.groupBox_Entete)
        self.lineEdit_text_remarque_ENT_cmd.setObjectName("lineEdit_text_remarque_ENT_cmd")
        self.horizontalLayout_16.addWidget(self.lineEdit_text_remarque_ENT_cmd)
        self.gridLayout.addLayout(self.horizontalLayout_16, 4, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_Entete)
        self.groupBox_Detail = QtWidgets.QGroupBox(self.widgetCentral)
        self.groupBox_Detail.setObjectName("groupBox_Detail")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Detail)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_FK_cmd = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_FK_cmd.setObjectName("label_FK_cmd")
        self.horizontalLayout_18.addWidget(self.label_FK_cmd)
        self.lineEdit_int_ld_cmd = QtWidgets.QLineEdit(self.groupBox_Detail)
        self.lineEdit_int_ld_cmd.setEnabled(False)
        self.lineEdit_int_ld_cmd.setObjectName("lineEdit_int_ld_cmd")
        self.horizontalLayout_18.addWidget(self.lineEdit_int_ld_cmd)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_code_unite = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_code_unite.setObjectName("label_code_unite")
        self.horizontalLayout_23.addWidget(self.label_code_unite)
        self.comboBox_code_unite = QtWidgets.QComboBox(self.groupBox_Detail)
        self.comboBox_code_unite.setObjectName("comboBox_code_unite")
        self.horizontalLayout_23.addWidget(self.comboBox_code_unite)
        self.gridLayout_2.addLayout(self.horizontalLayout_23, 0, 1, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_code_produit = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_code_produit.setObjectName("label_code_produit")
        self.horizontalLayout_19.addWidget(self.label_code_produit)
        self.comboBox_code_produit = QtWidgets.QComboBox(self.groupBox_Detail)
        self.comboBox_code_produit.setObjectName("comboBox_code_produit")
        self.horizontalLayout_19.addWidget(self.comboBox_code_produit)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_prix_global = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_prix_global.setObjectName("label_prix_global")
        self.horizontalLayout_24.addWidget(self.label_prix_global)
        self.lineEdit_float_prix_global = QtWidgets.QLineEdit(self.groupBox_Detail)
        self.lineEdit_float_prix_global.setEnabled(False)
        self.lineEdit_float_prix_global.setObjectName("lineEdit_float_prix_global")
        self.horizontalLayout_24.addWidget(self.lineEdit_float_prix_global)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 1, 1, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_Quantitedemd = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_Quantitedemd.setObjectName("label_Quantitedemd")
        self.horizontalLayout_20.addWidget(self.label_Quantitedemd)
        self.lineEdit_int_Quantitedemd = QtWidgets.QLineEdit(self.groupBox_Detail)
        self.lineEdit_int_Quantitedemd.setObjectName("lineEdit_int_Quantitedemd")
        self.horizontalLayout_20.addWidget(self.lineEdit_int_Quantitedemd)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 2, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_remarq = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_remarq.setObjectName("label_remarq")
        self.horizontalLayout_25.addWidget(self.label_remarq)
        self.lineEdit_text_remarq = QtWidgets.QLineEdit(self.groupBox_Detail)
        self.lineEdit_text_remarq.setObjectName("lineEdit_text_remarq")
        self.horizontalLayout_25.addWidget(self.lineEdit_text_remarq)
        self.gridLayout_2.addLayout(self.horizontalLayout_25, 2, 1, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_21.addWidget(self.label_12)
        self.lineEdit_real_prix_unitaire = QtWidgets.QLineEdit(self.groupBox_Detail)
        self.lineEdit_real_prix_unitaire.setObjectName("lineEdit_real_prix_unitaire")
        self.horizontalLayout_21.addWidget(self.lineEdit_real_prix_unitaire)
        self.gridLayout_2.addLayout(self.horizontalLayout_21, 3, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_util_DET_cmd = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_util_DET_cmd.setObjectName("label_util_DET_cmd")
        self.horizontalLayout_26.addWidget(self.label_util_DET_cmd)
        self.lineEdit_text_util_DET_cmd = QtWidgets.QLineEdit(self.groupBox_Detail)
        self.lineEdit_text_util_DET_cmd.setObjectName("lineEdit_text_util_DET_cmd")
        self.horizontalLayout_26.addWidget(self.lineEdit_text_util_DET_cmd)
        self.gridLayout_2.addLayout(self.horizontalLayout_26, 3, 1, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_dat_liv_souhaitee = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_dat_liv_souhaitee.setObjectName("label_dat_liv_souhaitee")
        self.horizontalLayout_22.addWidget(self.label_dat_liv_souhaitee)
        self.dateEdit_dat_liv_souhaitee = QtWidgets.QDateEdit(self.groupBox_Detail)
        self.dateEdit_dat_liv_souhaitee.setCalendarPopup(True)
        self.dateEdit_dat_liv_souhaitee.setObjectName("dateEdit_dat_liv_souhaitee")
        self.horizontalLayout_22.addWidget(self.dateEdit_dat_liv_souhaitee)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 4, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_flag_DET_cmd = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_flag_DET_cmd.setObjectName("label_flag_DET_cmd")
        self.horizontalLayout_27.addWidget(self.label_flag_DET_cmd)
        self.lineEdit_text_flag_DET_cmd = QtWidgets.QLineEdit(self.groupBox_Detail)
        self.lineEdit_text_flag_DET_cmd.setObjectName("lineEdit_text_flag_DET_cmd")
        self.horizontalLayout_27.addWidget(self.lineEdit_text_flag_DET_cmd)
        self.gridLayout_2.addLayout(self.horizontalLayout_27, 4, 1, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_remarque_DET_cmd = QtWidgets.QLabel(self.groupBox_Detail)
        self.label_remarque_DET_cmd.setObjectName("label_remarque_DET_cmd")
        self.horizontalLayout_28.addWidget(self.label_remarque_DET_cmd)
        self.lineEdit_remarque_DET_cmd = QtWidgets.QLineEdit(self.groupBox_Detail)
        self.lineEdit_remarque_DET_cmd.setObjectName("lineEdit_remarque_DET_cmd")
        self.horizontalLayout_28.addWidget(self.lineEdit_remarque_DET_cmd)
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 5, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.tableWidgetViewDetail = QtWidgets.QTableWidget(self.groupBox_Detail)
        self.tableWidgetViewDetail.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetViewDetail.setObjectName("tableWidgetViewDetail")
        self.tableWidgetViewDetail.setColumnCount(11)
        self.tableWidgetViewDetail.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewDetail.setHorizontalHeaderItem(10, item)
        self.tableWidgetViewDetail.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout_2.addWidget(self.tableWidgetViewDetail)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem1)
        self.pushButtonAjouterDetail = QtWidgets.QPushButton(self.groupBox_Detail)
        self.pushButtonAjouterDetail.setObjectName("pushButtonAjouterDetail")
        self.horizontalLayout_51.addWidget(self.pushButtonAjouterDetail)
        self.pushButtonModifierDetail = QtWidgets.QPushButton(self.groupBox_Detail)
        self.pushButtonModifierDetail.setEnabled(False)
        self.pushButtonModifierDetail.setObjectName("pushButtonModifierDetail")
        self.horizontalLayout_51.addWidget(self.pushButtonModifierDetail)
        self.pushButtonSupprimerDetail = QtWidgets.QPushButton(self.groupBox_Detail)
        self.pushButtonSupprimerDetail.setEnabled(False)
        self.pushButtonSupprimerDetail.setObjectName("pushButtonSupprimerDetail")
        self.horizontalLayout_51.addWidget(self.pushButtonSupprimerDetail)
        self.pushButtonInsererDetail = QtWidgets.QPushButton(self.groupBox_Detail)
        self.pushButtonInsererDetail.setEnabled(False)
        self.pushButtonInsererDetail.setObjectName("pushButtonInsererDetail")
        self.horizontalLayout_51.addWidget(self.pushButtonInsererDetail)
        self.pushButtonEffacerDetail = QtWidgets.QPushButton(self.groupBox_Detail)
        self.pushButtonEffacerDetail.setEnabled(False)
        self.pushButtonEffacerDetail.setObjectName("pushButtonEffacerDetail")
        self.horizontalLayout_51.addWidget(self.pushButtonEffacerDetail)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_51)
        self.verticalLayout_3.addWidget(self.groupBox_Detail)
        self.horizontalLayout_52.addLayout(self.verticalLayout_3)

        self.retranslateUi(EnteteDetail)
        QtCore.QMetaObject.connectSlotsByName(EnteteDetail)

    def retranslateUi(self, EnteteDetail):
        _translate = QtCore.QCoreApplication.translate
        EnteteDetail.setWindowTitle(_translate("EnteteDetail", "Form"))
        self.pushButtonNouveau.setText(_translate("EnteteDetail", "Nouveau"))
        self.pushButtonValider.setText(_translate("EnteteDetail", "Valider"))
        self.pushButtonRechercher.setText(_translate("EnteteDetail", "Rechercher"))
        self.pushButtonModifier.setText(_translate("EnteteDetail", "Modifier"))
        self.pushButtonSupprimer.setText(_translate("EnteteDetail", "Supprimer"))
        self.pushButtonPremier.setText(_translate("EnteteDetail", "Premier"))
        self.pushButtonDernier.setText(_translate("EnteteDetail", "Dernier"))
        self.pushButtonAvant.setText(_translate("EnteteDetail", "Avant"))
        self.pushButtonArriere.setText(_translate("EnteteDetail", "Arrierre"))
        self.pushButtonImprimer.setText(_translate("EnteteDetail", "Imprimier"))
        self.pushButtonImprimerTout.setText(_translate("EnteteDetail", "Imprimer tout"))
        self.pushButtonVisualiser.setText(_translate("EnteteDetail", "Visualiser"))
        self.groupBox_Entete.setTitle(_translate("EnteteDetail", "Entête"))
        self.label_code_cmd.setText(_translate("EnteteDetail", "code_cmd"))
        self.label_flag.setText(_translate("EnteteDetail", "flag"))
        self.label_refmarche.setText(_translate("EnteteDetail", "refmarche"))
        self.label_remarques.setText(_translate("EnteteDetail", "remarques"))
        self.label_code_frnsi.setText(_translate("EnteteDetail", "code_frnsi"))
        self.label_util_ENT_cmd.setText(_translate("EnteteDetail", "util_ENT_cmd"))
        self.label_code_societe.setText(_translate("EnteteDetail", "code_societe"))
        self.label_flag_ENT_cmd.setText(_translate("EnteteDetail", "flag_ENT_cmd"))
        self.label_11.setText(_translate("EnteteDetail", "date_cmd"))
        self.label_remarque_ENT_cmd.setText(_translate("EnteteDetail", "remarque_ENT_cmd"))
        self.groupBox_Detail.setTitle(_translate("EnteteDetail", "Detail"))
        self.label_FK_cmd.setText(_translate("EnteteDetail", "FK_cmd"))
        self.label_code_unite.setText(_translate("EnteteDetail", "code_unite"))
        self.label_code_produit.setText(_translate("EnteteDetail", "code_produit"))
        self.label_prix_global.setText(_translate("EnteteDetail", "prix_global"))
        self.label_Quantitedemd.setText(_translate("EnteteDetail", "Quantitedemd"))
        self.label_remarq.setText(_translate("EnteteDetail", "remarq"))
        self.label_12.setText(_translate("EnteteDetail", "prix_unitaire"))
        self.label_util_DET_cmd.setText(_translate("EnteteDetail", "util_DET_cmd"))
        self.label_dat_liv_souhaitee.setText(_translate("EnteteDetail", "dat_liv_souhaitee"))
        self.label_flag_DET_cmd.setText(_translate("EnteteDetail", "flag_DET_cmd"))
        self.label_remarque_DET_cmd.setText(_translate("EnteteDetail", "remarque_DET_cmd"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(0)
        item.setText(_translate("EnteteDetail", "FK_cmd"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(1)
        item.setText(_translate("EnteteDetail", "code_produit"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(2)
        item.setText(_translate("EnteteDetail", "Quantite"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(3)
        item.setText(_translate("EnteteDetail", "prix_unitaire"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(4)
        item.setText(_translate("EnteteDetail", "dat_liv_souhaitee"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(5)
        item.setText(_translate("EnteteDetail", "code_unite"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(6)
        item.setText(_translate("EnteteDetail", "prix_global"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(7)
        item.setText(_translate("EnteteDetail", "remarq"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(8)
        item.setText(_translate("EnteteDetail", "util_DET_cmd"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(9)
        item.setText(_translate("EnteteDetail", "flag_DET_cmd"))
        item = self.tableWidgetViewDetail.horizontalHeaderItem(10)
        item.setText(_translate("EnteteDetail", "remarque_DET_cmd"))
        self.pushButtonAjouterDetail.setText(_translate("EnteteDetail", "Ajouter"))
        self.pushButtonModifierDetail.setText(_translate("EnteteDetail", "Modifier"))
        self.pushButtonSupprimerDetail.setText(_translate("EnteteDetail", "Supprimer"))
        self.pushButtonInsererDetail.setText(_translate("EnteteDetail", "Inserer"))
        self.pushButtonEffacerDetail.setText(_translate("EnteteDetail", "Effacer"))
